
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import vn.com.dva.entities.DetailResultExam;
import vn.com.dva.entities.DetailTrain;
import vn.com.dva.entities.Exam;
import vn.com.dva.entities.LevelAll;
import vn.com.dva.entities.Question;
import vn.com.dva.entities.ResultExam;
import vn.com.dva.entities.Subject;
import vn.com.dva.entities.Train;
import vn.com.dva.entities.Users;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frm_SinhVien.java
 *
 * Created on Aug 12, 2011, 1:53:10 PM
 */
/**
 *
 * @author VietAnh
 */
public class Frm_SinhVien extends javax.swing.JFrame {

    private final ListenRoomSocket RoomChat;
    public static boolean isTest = false;
    private Long idUser ;

    /** Creates new form Frm_SinhVien */
    public Frm_SinhVien() {
        initComponents();
        RoomChat = new ListenRoomSocket(Session.user.getUserName());
        RoomChat.setTextPanelView(View);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelThongTin = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lbl = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        cbx = new javax.swing.JCheckBox();
        jCbQuyenHan = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jDate = new com.toedter.calendar.JDateChooser();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtLastLogin = new javax.swing.JTextField();
        jPanelThi = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        btnGui = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTKho = new javax.swing.JTextField();
        jTTB = new javax.swing.JTextField();
        jTDe1 = new javax.swing.JTextField();
        jCbMonThi = new javax.swing.JComboBox();
        jCbSoCau = new javax.swing.JComboBox();
        jCbDoKho = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        txtThoiGian = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLTrangthai = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtThoiGianKT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtConLaiKT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblDoKho = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtSocau = new javax.swing.JTextField();
        jCKyThi = new javax.swing.JComboBox();
        jbVaoThi = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtMonThiKT = new javax.swing.JTextField();
        dateStartsd = new javax.swing.JLabel();
        dateEnd = new javax.swing.JLabel();
        dateStart = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblLuotLam = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblTongSoLuotLam = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLichSu = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        View = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        Chat = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel13.setText("Thông Tin Cá Nhân");

        jLabel17.setText("Họ Tên Sinh Viên");

        jLabel18.setText("Tên Đăng Nhập");

        lbl.setText("                 ");

        jLabel20.setText("Ngày Sinh");

        jLabel21.setText("Địa Chỉ");

        jLabel19.setText("Mật Khẩu");

        jButton2.setText("Đổi Thông Tin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel24.setText("* Nếu không đổi mật khẩu thì giữ nguyên");

        cbx.setText("Kích hoạt");
        cbx.setEnabled(false);

        jCbQuyenHan.setEnabled(false);

        jLabel25.setText("Quyền hạn");

        jLabel27.setText("TEST ONLINE Version 1.02");

        jLabel28.setText("Develop by .....");

        jLabel22.setText("Lần đăng nhập cuối");

        javax.swing.GroupLayout jPanelThongTinLayout = new javax.swing.GroupLayout(jPanelThongTin);
        jPanelThongTin.setLayout(jPanelThongTinLayout);
        jPanelThongTinLayout.setHorizontalGroup(
            jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThongTinLayout.createSequentialGroup()
                .addContainerGap(800, Short.MAX_VALUE)
                .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27))
                .addContainerGap())
            .addGroup(jPanelThongTinLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThongTinLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addContainerGap())
                    .addGroup(jPanelThongTinLayout.createSequentialGroup()
                        .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelThongTinLayout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelThongTinLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(88, 88, 88)
                                        .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                                    .addGroup(jPanelThongTinLayout.createSequentialGroup()
                                        .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel25))
                                        .addGap(83, 83, 83)
                                        .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                            .addComponent(jCbQuyenHan, 0, 165, Short.MAX_VALUE)
                                            .addComponent(cbx)
                                            .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                            .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                            .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                            .addComponent(txtLastLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                                        .addGap(62, 62, 62))
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)))
                            .addGroup(jPanelThongTinLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(310, 310, 310))))
        );
        jPanelThongTinLayout.setVerticalGroup(
            jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel13)
                .addGap(48, 48, 48)
                .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl)
                    .addComponent(jLabel18))
                .addGap(22, 22, 22)
                .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtLastLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jCbQuyenHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbx)
                .addGap(12, 12, 12)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(27, 27, 27)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông Tin", new javax.swing.ImageIcon(getClass().getResource("/resource/Profile.png")), jPanelThongTin); // NOI18N

        jScrollPane1.setViewportView(jTextPane1);

        jScrollPane2.setViewportView(jTextPane2);

        btnGui.setText("Gửi");
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Luyện Tập"));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Môn Thi");

        jLabel2.setText("Số Câu");

        jLabel3.setText("Thời Gian");

        jLabel4.setText("Độ Khó");

        jLabel5.setText("Khó");

        jLabel6.setText("Trung Bình");

        jLabel7.setText("Dễ");

        jCbMonThi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCbSoCau.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCbDoKho.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbDoKhoItemStateChanged(evt);
            }
        });

        jButton1.setText("Bắt Đầu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTKho, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTTB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTDe1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtThoiGian)
                        .addComponent(jCbDoKho, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCbSoCau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCbMonThi, 0, 128, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCbMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jCbSoCau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jCbDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jTDe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLTrangthai.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLTrangthai.setText("Còn lại");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel8.setText("Ngày KT");

        txtThoiGianKT.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel9.setText("Thời gian");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel10.setText("Môn thi");

        txtConLaiKT.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Ngày BĐ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel12.setText("phút");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel14.setText("Kỳ thi");

        lblDoKho.setText("Dễ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel15.setText("Số câu");

        txtSocau.setText("10");
        txtSocau.setEnabled(false);

        jCKyThi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCKyThi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCKyThiItemStateChanged(evt);
            }
        });

        jbVaoThi.setFont(new java.awt.Font("Tahoma", 1, 11));
        jbVaoThi.setText("VÀO THI");
        jbVaoThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbVaoThiVaothi(evt);
            }
        });
        jbVaoThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVaoThiActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel16.setText("Độ khó");

        txtMonThiKT.setEnabled(false);

        dateEnd.setText("jLabel27");

        dateStart.setText("jLabel37");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel23.setText("Đc làm");

        lblLuotLam.setText("jLabel37");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel26.setText("Tổng lượt");

        lblTongSoLuotLam.setText("jLabel27");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jbVaoThi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblLuotLam, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dateStart, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(dateStartsd, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtSocau, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtThoiGianKT, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCKyThi, 0, 146, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(15, 15, 15))
                                    .addComponent(jLTrangthai, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMonThiKT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(dateEnd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                        .addComponent(txtConLaiKT))
                                    .addGap(3, 3, 3))))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTongSoLuotLam, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtMonThiKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCKyThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(dateStartsd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateStart)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(dateEnd))))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLTrangthai)
                        .addComponent(txtConLaiKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtThoiGianKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDoKho)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSocau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblLuotLam)
                    .addComponent(jLabel26)
                    .addComponent(lblTongSoLuotLam))
                .addGap(22, 22, 22)
                .addComponent(jbVaoThi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lịch Sử"));

        jTableLichSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableLichSu);

        jButton4.setText("Luyện Tập");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Kỳ Thi");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Xem Lại");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelThiLayout = new javax.swing.GroupLayout(jPanelThi);
        jPanelThi.setLayout(jPanelThiLayout);
        jPanelThiLayout.setHorizontalGroup(
            jPanelThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, 0, 366, Short.MAX_VALUE)
                    .addGroup(jPanelThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanelThiLayout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnGui))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelThiLayout.setVerticalGroup(
            jPanelThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThiLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelThiLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelThiLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnGui, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Luyện - Thi", new javax.swing.ImageIcon(getClass().getResource("/resource/Test Icon.jpg")), jPanelThi); // NOI18N

        jScrollPane5.setViewportView(View);

        Chat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ChatKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(Chat);

        jButton3.setText("Gửi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Giao Tiếp", new javax.swing.ImageIcon(getClass().getResource("/resource/Comment.png")), jPanel4); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 937, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel5 = new Pnl_ThongKe();

        jTabbedPane1.addTab("Thống Kê", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 937, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel6 = new Pnl_TinTuc();

        jTabbedPane1.addTab("Tin Tức", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        loadform();
    }//GEN-LAST:event_formWindowOpened

    private void ChatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ChatKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n') {
            if (evt.isControlDown()) {
                Chat.setText(Chat.getText() + "\n");
            } else {
                String Message = Chat.getText();
                RoomChat.writeMessage_on_panelView("Me" + ": " + Message);
                Chat.setText("");
                try {
                    RoomChat.Chatting(Message + "\n");
                } catch (Exception e) {
                }
            }
        }
}//GEN-LAST:event_ChatKeyTyped

    private void jbVaoThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVaoThiActionPerformed
        // TODO add your handling code here:
        if (isTest == true) return;
        isTest = true;
        // TODO add your handling code here:
        Exam exam;
        try {
            exam = (Exam) jCKyThi.getSelectedItem();
        } catch (Exception ex) {
            return;
        }
        //dang lam do . quay lai sau
        Session.kythi = exam;
        // Ngay
        Calendar c = Calendar.getInstance();
        
        Session.ngaythi = c;
        Session.socauhoi = exam.getNumberQuestion();
        try {
            Session.monthi = Cl_Client.c.getSubjectByID(exam.getSubjectID());
            Session.dokho = Cl_Client.c.getLeveltByID(exam.getLevelID());
        } catch (RemoteException ex) {
            Logger.getLogger(Frm_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        Session.thoigian = exam.getTimes();

        FrmThi a = new FrmThi();
        a.setVisible(true);
    }//GEN-LAST:event_jbVaoThiActionPerformed

    private void jbVaoThiVaothi(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVaoThiVaothi
}//GEN-LAST:event_jbVaoThiVaothi

    private void jCKyThiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCKyThiItemStateChanged
        try {
            // TODO add your handling code here:
            if (evt.getItem() == null) {
                resetPanelExam();
                return;
            }
            if (jCKyThi.getSelectedIndex() == 0) {
                resetPanelExam();
                return;
            }
            Exam e = (Exam) jCKyThi.getSelectedItem();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            txtMonThiKT.setText(Cl_Client.c.getSubjectByID(e.getSubjectID()).getSubjectName());
            dateStart.setText(sdf.format(e.getDateStart().getTime()));
            dateEnd.setText(sdf.format(e.getDateEnd().getTime()));
            txtThoiGianKT.setText(e.getTimes() + "");
            txtConLaiKT.setText("Đang tính");
            // So cau hoi lay ra tu table kythi-cauhoi
            txtSocau.setText(e.getNumberOfTest() + "");
            lblLuotLam.setText(e.getNumberOfTest() + "");
            lblTongSoLuotLam.setText(Cl_Client.c.getTotalTestOfExam(e)+"");

        } catch (RemoteException ex) {
            Logger.getLogger(Frm_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jCKyThiItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (FrmThi.isOpen == true) {
            JOptionPane.showMessageDialog(null, "Đang luyện tập");
            return;
        }
        try {
            // TODO add your handling code here:
            isTest = false;
            if (jCbMonThi.getSelectedIndex() == 0 || jCbDoKho.getSelectedIndex() == 0 || jCbSoCau.getSelectedIndex() == 0) {
                return;
            }
            Subject monthi = (Subject) jCbMonThi.getSelectedItem();
            int socau = Integer.parseInt(jCbSoCau.getSelectedItem().toString());
            String thoigian = txtThoiGian.getText();
            LevelAll dokho = (LevelAll) jCbDoKho.getSelectedItem();
            // Lưu lại các thông tin
            Session.monthi = monthi;
            Session.socauhoi = socau;
            Session.thoigian = Integer.parseInt(thoigian);
            Session.dokho = dokho;

            // Ngay
            Session.ngaythi = Calendar.getInstance();
            Session.kythi = null;

            //
            if (socau > Cl_Client.c.getAllQuestionBySubject(monthi.getSubjecId()).size()) {
                Cl_Client.ShowError("Không đủ câu hỏi");
                return;
            }
            this.dispose();
            FrmThi a = new FrmThi();
            FrmThi.isOpen = true;
            a.setVisible(true);

        } catch (RemoteException ex) {
            Logger.getLogger(Frm_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCbDoKhoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbDoKhoItemStateChanged
        if (jCbDoKho.getSelectedIndex() > 0) {
            LevelAll level = (LevelAll) jCbDoKho.getSelectedItem();
            jTKho.setText(level.getPercentHard() + "");
            jTTB.setText(level.getPercentNormal() + "");
            jTDe1.setText(level.getPercentEasy() + "");
        }
}//GEN-LAST:event_jCbDoKhoItemStateChanged

    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnGuiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf= new SimpleDateFormat("dd-MM-yyyy");
        try {
            String diachi = txtDiaChi.getText();
            String birthday;
            try {
                birthday = sdf.format(jDate.getCalendar().getTime());
            } catch(Exception ex){
                birthday = "";
            }
            String password = pass.getText();
            if (password.length()  <= 3) {
                JOptionPane.showMessageDialog(null, " Mật khẩu quá ngắn");
                return;
            }
            String name = txtHoTen.getText();
            if (name.length() <3 ) {
                JOptionPane.showMessageDialog(null, " Vui lòng điền tên thật của bạn ");
                return;
            }
            Users bean = Session.user ;
            bean.setAddress(diachi);
            bean.setPassword(password);
            bean.setBirthday(birthday);
            bean.setFullName(name);
            boolean k = Cl_Client.c.updateUser(bean);
            if (k) {
                Cl_Client.ShowSuccess("Cập nhật thành công");
                
            } else {
                Cl_Client.ShowError("Lỗi rồi");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_CauHoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            jTableLichSu.setModel(Cl_Client.c.getAllTraintoTableByIdUser(idUser));
        } catch (RemoteException ex) {
            Logger.getLogger(Frm_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            jTableLichSu.setModel(Cl_Client.c.getAllExamtoTableByIdUser(idUser));
        } catch (RemoteException ex) {
            Logger.getLogger(Frm_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        List<Question> list = new ArrayList<Question>();
        List<String> choose = new ArrayList<String>();
        List<String> answerRandom = new ArrayList<String>();
        int row = jTableLichSu.getSelectedRow() ;
        if (row == -1){
            JOptionPane.showMessageDialog(null, " Chưa chọn kỳ thi nào !");
            return ;
        } 
        try {
            Train train = (Train) jTableLichSu.getValueAt(row , 0);
            Subject subject = (Subject) jTableLichSu.getValueAt(row , 1);
            DetailTrain bean = Cl_Client.c.getDetailTrainByTrainID(train.getTrainID());
            List<Long> lst = bean.getListIdQuestion();
            int i = 0 ;
            for (i=0; i<lst.size();i++){
                Object obj = lst.get(i);
                long idLong = Long.valueOf(obj.toString());
                Long lObj = new Long(idLong);
                list.add(Cl_Client.c.getQuestiontByID(lObj));
            }
            choose = bean.getListIdAnswer();
            answerRandom = bean.getListAnswerRandom();
            int trueQuestion = (int) (train.getScore()*train.getTotalQuestion());
            FrmKetQuaThi kq = new FrmKetQuaThi(list, choose, answerRandom, subject, train.getTotalQuestion() , trueQuestion,true);
            kq.setVisible(true);
        } catch(Exception ex){
            System.out.print(ex);
        }
        
        try {
            ResultExam re =  (ResultExam) jTableLichSu.getValueAt(row , 0);
            Exam exam = (Exam) jTableLichSu.getValueAt(row , 1);
            Subject subject = (Subject) jTableLichSu.getValueAt(row , 2);
            DetailResultExam bean = Cl_Client.c.getDetailResultExamByResultExamID(re.getId());
            List<Long> lst = bean.getListIdQuestion();
            int i = 0 ;
            for (i=0; i<lst.size();i++){
                Object obj = lst.get(i);
                long idLong = Long.valueOf(obj.toString());
                Long lObj = new Long(idLong);
                list.add(Cl_Client.c.getQuestiontByID(lObj));
            }
            choose = bean.getListIdAnswer();
            answerRandom = bean.getListAnswerRandom();
            int trueQuestion = (int) (re.getScore()*exam.getNumberQuestion()/100);
            FrmKetQuaThi kq = new FrmKetQuaThi(list, choose, answerRandom, subject, exam.getNumberQuestion() , trueQuestion, true);
            kq.setVisible(true);
        } catch(Exception ex){
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    
    
    public void loadform() {
        try {
            Users user = Session.user;
            idUser = user.getUserID();
            // --------------- load table 
            // Lich su thi
            jTableLichSu.setModel(Cl_Client.c.getAllTrainToTable());
            // ------------------  Tab Thi  --------------------------
            String username = user.getUserName();
            //String id = Cl_Client.c.getIDUser(user);

            // Add mon thi
            jCbMonThi.removeAllItems();
            List<Subject> allSubject = Cl_Client.c.getAllSubject();
            jCbMonThi.addItem("Lựa Chọn");
            if (allSubject.size() > 0) {
                for (int i = 0; i < allSubject.size(); i++) {
                    jCbMonThi.addItem(allSubject.get(i));
                }
            }
            // Add do kho
            jCbDoKho.removeAllItems();
            jCbDoKho.addItem("Lựa Chọn");
            List<LevelAll> allLevel = Cl_Client.c.getAllLevel();
            if (allLevel.size() > 0) {
                for (int i = 0; i < allLevel.size(); i++) {
                    jCbDoKho.addItem(allLevel.get(i));
                }
            }
            // so cau
            jCbSoCau.removeAllItems();
            jCbSoCau.addItem("Lựa Chọn");
            jCbSoCau.addItem(1);
            for (int i = 2; i <= 20; i++) {
                jCbSoCau.addItem(i);
            }

            // Ky Thi dang dien ra
            List<Exam> currentExam = Cl_Client.c.getCurrentExam();
            jCKyThi.addItem("Lựa Chọn");
            if (!currentExam.isEmpty()) {
                for (int i = 0; i < currentExam.size(); i++) {
                    jCKyThi.addItem(currentExam.get(i));
                }
            }

            // ------------  Tab Thông Tin Tài Khoản  ------------------
            // Hien thị thông tin sinh viên lên
            if (user.getEnable()) {
                cbx.setSelected(true);
            } else {
                cbx.setSelected(false);
            }
            pass.setText(user.getPassword());
            // Thông tin cá nhân
            lbl.setText(username);
            txtHoTen.setText(user.getFullName());
            txtLastLogin.setText(user.getLastLoginDate());
            try {
                String dateString = user.getBirthday();
                String s[] = dateString.split("-");
                int year = Integer.parseInt(s[2])-1900;
                int month = Integer.parseInt(s[1])- 1;
                int date = Integer.parseInt(s[0]);
                Date d = new Date(year, month, date);
                jDate.setDate(d);
            } catch(Exception e){
                
            }
            txtDiaChi.setText(user.getAddress());
        } catch (RemoteException ex) {
            Logger.getLogger(Frm_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frm_SinhVien().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Chat;
    private javax.swing.JTextPane View;
    private javax.swing.JButton btnGui;
    private javax.swing.JCheckBox cbx;
    private javax.swing.JLabel dateEnd;
    private javax.swing.JLabel dateStart;
    private javax.swing.JLabel dateStartsd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jCKyThi;
    private javax.swing.JComboBox jCbDoKho;
    private javax.swing.JComboBox jCbMonThi;
    private javax.swing.JComboBox jCbQuyenHan;
    private javax.swing.JComboBox jCbSoCau;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLTrangthai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelThi;
    private javax.swing.JPanel jPanelThongTin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTDe1;
    private javax.swing.JTextField jTKho;
    private javax.swing.JTextField jTTB;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableLichSu;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JButton jbVaoThi;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblDoKho;
    private javax.swing.JLabel lblLuotLam;
    private javax.swing.JLabel lblTongSoLuotLam;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField txtConLaiKT;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLastLogin;
    private javax.swing.JTextField txtMonThiKT;
    private javax.swing.JTextField txtSocau;
    private javax.swing.JTextField txtThoiGian;
    private javax.swing.JTextField txtThoiGianKT;
    // End of variables declaration//GEN-END:variables


    private void resetPanelExam(){
        txtMonThiKT.setText("");
        dateStart.setText("");
        dateEnd.setText("");
        txtThoiGianKT.setText("");
        txtConLaiKT.setText("");
        txtSocau.setText("");
        lblLuotLam.setText("");
        lblTongSoLuotLam.setText("");
    }




}
