

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frm_Admin.java
 *
 * Created on Jul 30, 2011, 8:21:07 PM
 */

/**
 *
 * @author VietAnh
 */
public class Frm_Admin extends javax.swing.JFrame {

    /** Creates new form Frm_Admin */
    public Frm_Admin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        jPanelMain = new javax.swing.JPanel();
        jPTaiKhoan = new javax.swing.JPanel();
        jPMonHoc = new javax.swing.JPanel();
        jPCauHoi = new javax.swing.JPanel();
        jPKyThi = new javax.swing.JPanel();
        jPDoKho = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                ActiveWindow(evt);
            }
        });

        tabMain.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabMain.setFont(new java.awt.Font("Tahoma", 0, 14));
        tabMain.setPreferredSize(new java.awt.Dimension(893, 562));

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        jPanelMain = new Pnl_MainForm();

        tabMain.addTab("Trang Chủ", new javax.swing.ImageIcon(getClass().getResource("/resource/home1.png")), jPanelMain); // NOI18N

        javax.swing.GroupLayout jPTaiKhoanLayout = new javax.swing.GroupLayout(jPTaiKhoan);
        jPTaiKhoan.setLayout(jPTaiKhoanLayout);
        jPTaiKhoanLayout.setHorizontalGroup(
            jPTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        jPTaiKhoanLayout.setVerticalGroup(
            jPTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        jPTaiKhoan = new Pnl_TaiKhoan();

        tabMain.addTab("Tài Khoản", new javax.swing.ImageIcon(getClass().getResource("/resource/Profile.png")), jPTaiKhoan); // NOI18N

        javax.swing.GroupLayout jPMonHocLayout = new javax.swing.GroupLayout(jPMonHoc);
        jPMonHoc.setLayout(jPMonHocLayout);
        jPMonHocLayout.setHorizontalGroup(
            jPMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        jPMonHocLayout.setVerticalGroup(
            jPMonHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        jPMonHoc = new Pnl_MonHoc();

        tabMain.addTab("Môn Học", new javax.swing.ImageIcon(getClass().getResource("/resource/Bar Chart.png")), jPMonHoc); // NOI18N

        javax.swing.GroupLayout jPCauHoiLayout = new javax.swing.GroupLayout(jPCauHoi);
        jPCauHoi.setLayout(jPCauHoiLayout);
        jPCauHoiLayout.setHorizontalGroup(
            jPCauHoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        jPCauHoiLayout.setVerticalGroup(
            jPCauHoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        jPCauHoi = new Pnl_CauHoi();

        tabMain.addTab("Câu Hỏi", new javax.swing.ImageIcon(getClass().getResource("/resource/cau hoi.png")), jPCauHoi); // NOI18N

        javax.swing.GroupLayout jPKyThiLayout = new javax.swing.GroupLayout(jPKyThi);
        jPKyThi.setLayout(jPKyThiLayout);
        jPKyThiLayout.setHorizontalGroup(
            jPKyThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        jPKyThiLayout.setVerticalGroup(
            jPKyThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        jPKyThi = new Pnl_KyThi();

        tabMain.addTab("Kỳ Thi", new javax.swing.ImageIcon(getClass().getResource("/resource/Ky Thi.png")), jPKyThi); // NOI18N

        javax.swing.GroupLayout jPDoKhoLayout = new javax.swing.GroupLayout(jPDoKho);
        jPDoKho.setLayout(jPDoKhoLayout);
        jPDoKhoLayout.setHorizontalGroup(
            jPDoKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        jPDoKhoLayout.setVerticalGroup(
            jPDoKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        jPDoKho = new Pnl_DoKho();

        tabMain.addTab("Độ Khó", new javax.swing.ImageIcon(getClass().getResource("/resource/Do Kho.png")), jPDoKho); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );

        jPanel3 = new Pnl_BackUpData();

        tabMain.addTab("BackUp", new javax.swing.ImageIcon(getClass().getResource("/resource/Comment.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActiveWindow(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ActiveWindow
        // TODO add your handling code here:
        loadform();
    }//GEN-LAST:event_ActiveWindow

    /**
    * @param args the command line arguments
    */

    public void loadform()
    {
        new Cl_Client();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPCauHoi;
    private javax.swing.JPanel jPDoKho;
    private javax.swing.JPanel jPKyThi;
    private javax.swing.JPanel jPMonHoc;
    private javax.swing.JPanel jPTaiKhoan;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables

}
