/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmDKTaiKhoan.java
 *
 * Created on Sep 12, 2011, 8:36:26 PM
 */

/**
 *
 * @author VietAnh
 */

import java.awt.Color;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class FrmDKTaiKhoan extends javax.swing.JFrame {

    /** Creates new form FrmDKTaiKhoan */
    public FrmDKTaiKhoan() {
        initComponents();
        loadform();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCheck = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        pass2 = new javax.swing.JPasswordField();
        lblDoManh = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCbNgay = new javax.swing.JComboBox();
        jCbThang = new javax.swing.JComboBox();
        jCbNam = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCbLop = new javax.swing.JComboBox();
        lbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtCauHoi = new javax.swing.JTextField();
        jCbCauHoi = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        txtTraLoi = new javax.swing.JTextField();
        lblCauHoi = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCheck.setText("jLabel5");

        btnThem.setText("Đăng Ký");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên đăng nhập");

        btnHuy.setText("Làm Lại");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        pass2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pass2CaretUpdate(evt);
            }
        });

        lblDoManh.setForeground(new java.awt.Color(51, 102, 255));
        lblDoManh.setText("Yếu");

        pass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                passCaretUpdate(evt);
            }
        });

        jLabel3.setText("Nhập lại mật khẩu");

        jLabel2.setText("Mật khẩu");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin cá nhân"));

        jLabel7.setText("Họ tên");

        jLabel8.setText("Ngày Sinh");

        jLabel9.setText("Địa chỉ");

        jLabel10.setText("Lớp");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCbLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lbl.setText("ok");

        jLabel6.setText("Độ mạnh :");

        jButton1.setText("Kiểm tra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCbCauHoi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbCauHoiItemStateChanged(evt);
            }
        });

        jLabel23.setText("Câu Hỏi Bí Mật");

        lblCauHoi.setText("Câu Hỏi");

        jLabel24.setText("Trả Lời");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblCauHoi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCauHoi))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(txtTraLoi, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(156, 156, 156)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCbCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(439, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(pass)
                            .addComponent(jLabel3)
                            .addComponent(pass2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(lbl)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblDoManh))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblCheck)))
                        .addGap(158, 158, 158)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblDoManh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCheck)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(11, 11, 11)
                        .addComponent(jCbCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCauHoi)
                            .addComponent(txtCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTraLoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            if (!Cl_Client.c.checkUsername(txtUsername.getText())) {
                Cl_Client.ShowError("Đã tồn tại tên đăng nhập ! Vui lòng chọn tên khác");
                return ;
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_CauHoi.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (txtUsername.getText().equals("") || pass.getText().equals("")|| pass2.getText().equals("") || txtHoTen.getText().equals("")) {
            Cl_Client.ShowError("Hãy nhập đầy đủ thông tin !");
            return;
        }
        if (!pass.getText().equals(pass2.getText())) {
            Cl_Client.ShowError("Sai password rồi !");
            return;
        }

        if (jCbCauHoi.getSelectedIndex()== 0)
            {
                Cl_Client.ShowError("Bạn phải chọn 1 câu hỏi bí mật !!!");
                return;
            }

            if (jCbCauHoi.getSelectedIndex() == 7 && txtCauHoi.getText().equals(""))
            {
                Cl_Client.ShowError("Bạn hãy nhập nội dung câu hỏi !!!");
                return;
            }

            if (txtTraLoi.getText().equals(""))
            {
                Cl_Client.ShowError(" Hãy nhập câu trả lời !!!");
                return;
            }
            if (txtTraLoi.getText().length() < 2)
            {
                Cl_Client.ShowError(" Câu trả lời có ít nhất 2 ký tự!!!");
                return;
            }


            String cauhoi ="";
            if (jCbCauHoi.getSelectedIndex() != 7 )
                cauhoi = jCbCauHoi.getSelectedItem().toString();
            else
                cauhoi = txtCauHoi.getText();

            String traloi = txtTraLoi.getText();


        String r[] = jCbThang.getSelectedItem().toString().split(" ");
        String ngaysinh = jCbNam.getSelectedItem().toString()+"-"+r[1]+"-"+jCbNgay.getSelectedItem().toString();
        String ok = "0";
        try {
            boolean k = Cl_Client.c.addTaiKhoanFull(txtUsername.getText(), pass.getText(), "Sinh Viên" , ok, txtHoTen.getText(), ngaysinh, txtDiaChi.getText(), jCbLop.getSelectedItem().toString(),cauhoi,traloi);
            if (k) {
                Cl_Client.ShowSuccess("Đăng Ký Thành Công !!");
                this.dispose();
                new FrmLogon().show();
            } else {
                Cl_Client.ShowError("Đăng Ký Thất Bại !");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(FrmDKTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        resetAll();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void pass2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pass2CaretUpdate
        // TODO add your handling code here:
        if (pass.getText().equals(pass2.getText())) {
            lblCheck.setText("OK");
        } else lblCheck.setText("Sai");
}//GEN-LAST:event_pass2CaretUpdate

    private void passCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_passCaretUpdate
        // TODO add your handling code here:
        if (pass.getText().length() <5) {
            lblDoManh.setForeground(new java.awt.Color(51, 102, 255));
            lblDoManh.setText("Yếu");
        }

        if (pass.getText().length() >=5 && pass.getText().length() <= 7 ) {
            lblDoManh.setForeground(Color.BLUE);
            lblDoManh.setText("Trung Bình");
        }
        if (pass.getText().length() >=8) {
            lblDoManh.setForeground(Color.RED);
            lblDoManh.setText("Mạnh");
        }
}//GEN-LAST:event_passCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            if (Cl_Client.c.checkUsername(txtUsername.getText())) {
                lbl.setForeground(Color.BLUE);
                lbl.setText("Có thể sử dụng");
            } else {
                lbl.setForeground(Color.RED);
                lbl.setText("Đã tồn tại!!!");
            }

        } catch (RemoteException ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCbCauHoiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbCauHoiItemStateChanged
        // TODO add your handling code here:
        int id = jCbCauHoi.getSelectedIndex();

        if (id == 7) {
            lblCauHoi.setVisible(true);
            txtCauHoi.setVisible(true);
        } else {
            lblCauHoi.setVisible(false);
            txtCauHoi.setVisible(false);
        }
}//GEN-LAST:event_jCbCauHoiItemStateChanged

     private void resetAll() {
       txtUsername.setText("");
       pass.setText("");
       pass2.setText("");
       txtHoTen.setText("");
       jCbNgay.setSelectedItem("1");
       jCbThang.setSelectedItem("1");
       jCbNam.setSelectedItem("2010");
       txtDiaChi.setText("");
       lbl.setText("");
       lblDoManh.setText("Điền mật khẩu");
       lblCheck.setText("Sai");
       txtCauHoi.setText("");
       txtTraLoi.setText("");
    }

     public void loadform()
     {
       // Lớp
        jCbLop.addItem("Lựa Chọn");
        jCbLop.addItem("CNPM");
        jCbLop.addItem("MMT");
        jCbLop.addItem("HTTT");
        jCbLop.addItem("KHMT");
        jCbLop.addItem("Khác");

        // Ngày tháng năm
        jCbNgay.removeAllItems();
        jCbThang.removeAllItems();
        jCbNam.removeAllItems();
        jCbLop.removeAllItems();
        int i ;
        for (i=1;i<=31;i++)
            if (i<=9)
            {
                jCbNgay.addItem("0"+i);
            }
            else jCbNgay.addItem(""+i);
        for (i=1;i<=12;i++)
            if (i<=9)
            {
                jCbThang.addItem("Tháng 0"+i);
            }
            else
            {
                jCbThang.addItem("Tháng "+i);
            }
        for (i = 2010; i>=1950;i--)
        {
            jCbNam.addItem(""+i);
        }
        //Lớp
        jCbLop.addItem("CNPM");
        jCbLop.addItem("MMT");
        jCbLop.addItem("HTTT");
        jCbLop.addItem("KHMT");
        jCbLop.addItem("Khác");
        // Câu Hỏi bí mật
        jCbCauHoi.removeAllItems();
        jCbCauHoi.addItem("Chọn một?");
        jCbCauHoi.addItem("Cha của bạn sinh ra ở thành phố nào ?");
        jCbCauHoi.addItem("Tên trường tiểu học của bạn là gì ?");
        jCbCauHoi.addItem("Con vật cưng đầu tiên của bạn tên gì ?");
        jCbCauHoi.addItem("Nhân vật trong phim mà bạn thích nhất là ai ?");
        jCbCauHoi.addItem("Tên nhạc sĩ bạn thích nhất ?");
        jCbCauHoi.addItem("Món khoái khẩu lúc bạn còn nhỏ là gì ?");
        jCbCauHoi.addItem("-- Nhập câu hỏi của bạn tại đây --");

        lblCauHoi.setVisible(false);
        txtCauHoi.setVisible(false);


     }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDKTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCbCauHoi;
    private javax.swing.JComboBox jCbLop;
    private javax.swing.JComboBox jCbNam;
    private javax.swing.JComboBox jCbNgay;
    private javax.swing.JComboBox jCbThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblCauHoi;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblDoManh;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JTextField txtCauHoi;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtTraLoi;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
