
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import vn.com.dva.entities.Question;
import vn.com.dva.entities.Subject;
import vn.com.dva.entities.Users;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmThemCauHoi.java
 *
 * Created on Aug 16, 2011, 4:19:36 PM
 */

/**
 *
 * @author VietAnh
 */
public class FrmThemCauHoi extends javax.swing.JFrame {

    private byte[] dataImages;
    private boolean isEdit = false; 
    private Question q ;
    /** Creates new form FrmThemCauHoi */
    public FrmThemCauHoi() {
        initComponents();
        isEdit = false; 
    }
    public FrmThemCauHoi(Question q){
        isEdit = true ;
        this.q  = q ;
    }
     public byte[] getDataImages() {
        return dataImages;
    }
    public FrmThemCauHoi(boolean isInsert){
        initComponents();
        if (isInsert) {
            this.btnSua.setEnabled(false);
        }else{
            this.btnThem.setText("Thêm Mới");
            this.btnSua.setEnabled(true);
        }
        loadform();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTpNoiDung = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jRdA = new javax.swing.JRadioButton();
        jRdC = new javax.swing.JRadioButton();
        jRdB = new javax.swing.JRadioButton();
        jRdD = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTpA = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTpB = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTpC = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTpD = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCbMonThi = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jCbDoKho = new javax.swing.JComboBox();
        btnThem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        lblPhoto = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        txtTieuDe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTpNoiDung.setBorder(javax.swing.BorderFactory.createTitledBorder("Nội dung câu hỏi"));
        jScrollPane1.setViewportView(jTpNoiDung);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Đáp Án"));

        buttonGroup1.add(jRdA);
        jRdA.setText("A");

        buttonGroup1.add(jRdC);
        jRdC.setText("C");

        buttonGroup1.add(jRdB);
        jRdB.setText("B");

        buttonGroup1.add(jRdD);
        jRdD.setText("D");

        jScrollPane2.setViewportView(jTpA);

        jScrollPane3.setViewportView(jTpB);

        jScrollPane4.setViewportView(jTpC);

        jScrollPane5.setViewportView(jTpD);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRdA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRdC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRdB)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRdD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRdB)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRdA)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRdC)
                                .addComponent(jRdD))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addGap(32, 32, 32)))
                .addGap(45, 45, 45))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 204), null));

        jLabel1.setText("Môn Thi");

        jCbMonThi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Độ Khó");

        jCbDoKho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCbMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jCbDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCbMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCbDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        lblPhoto.setText("jLabel3");
        lblPhoto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lblPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhotoMouseClicked(evt);
            }
        });

        btnSua.setText("Sửa");

        jLabel3.setText("Tiêu đề câu hỏi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txtTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnThoat, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addComponent(btnSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)
                        .addGap(16, 16, 16)
                        .addComponent(btnThoat)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSua, btnThem, btnThoat});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        loadform();
    }//GEN-LAST:event_formWindowOpened

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // TODO add your handling code here:
            if (jTpNoiDung.getText().equals("")) {
                Cl_Client.ShowError("Bạn chưa nhập nội dung câu hỏi");
                return;
            }
            if (jTpA.getText().equals("") || jTpB.getText().equals("") || jTpC.getText().equals("") || jTpD.getText().equals("")) {
                Cl_Client.ShowError("Bạn phải nhập đầy đủ đáp án");
            }
            String da = "";
            if (jRdA.isSelected()) {
                da = "A";
            }
            if (jRdB.isSelected()) {
                da = "B";
            }
            if (jRdC.isSelected()) {
                da = "C";
            }
            if (jRdD.isSelected()) {
                da = "D";
            }
            if (da.equals("")) {
                Cl_Client.ShowError("Bạn phải chọn 1 đáp án đúng");
                return;
            }

            // zooooooooooozozozozozozzzz
            Users u = Session.user ;
            Long idUser = u.getUserID();
            
            Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                String dateCreate = sdf.format(d);
                
            byte[] image = getDataImages();
            Question bean = new Question(da, idUser , jCbDoKho.getSelectedIndex()+1 , 0L,jTpNoiDung.getText(),da, jTpA.getText(), jTpB.getText(),
                    jTpC.getText(), jTpD.getText(), dateCreate, image );
            
            if (Cl_Client.c.insertQuestion(bean)){
                resetAll();
                loadform();
            }
            else {
                JOptionPane.showMessageDialog(null, "Loi");
            }
            

        } catch (RemoteException ex) {
            Logger.getLogger(FrmThemCauHoi.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnThemActionPerformed

private void lblPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhotoMouseClicked
// TODO add your handling code here:
    if (evt.getClickCount() == 2) {
        loadImage();
    }
}//GEN-LAST:event_lblPhotoMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmThemCauHoi().setVisible(true);
            }
        });
    }

    private void resetAll()
    {
        jTpNoiDung.setText("");
        jTpA.setText("");
        jTpB.setText("");
        jTpC.setText("");
        jTpD.setText("");
        buttonGroup1.clearSelection();
    }
      private void loadform() {
        // Độ khó
        jCbDoKho.removeAllItems();
        jCbDoKho.addItem("Khó");
        jCbDoKho.addItem("Trung Bình");
        jCbDoKho.addItem("Dễ");
        // Môn học
        jCbMonThi.removeAllItems();
        List<Subject> lst ;
        try {
            lst = Cl_Client.c.getAllSubject();
            if (!lst.isEmpty())
                for (Subject bean : lst){
                    jCbMonThi.addItem(bean);
                }
        } catch (RemoteException ex) {
            Logger.getLogger(FrmThemCauHoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox jCbDoKho;
    private javax.swing.JComboBox jCbMonThi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRdA;
    private javax.swing.JRadioButton jRdB;
    private javax.swing.JRadioButton jRdC;
    private javax.swing.JRadioButton jRdD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTpA;
    private javax.swing.JTextPane jTpB;
    private javax.swing.JTextPane jTpC;
    private javax.swing.JTextPane jTpD;
    private javax.swing.JTextPane jTpNoiDung;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JTextField txtTieuDe;
    // End of variables declaration//GEN-END:variables


      private void loadImage() {
        JFileChooser fileChoise = new JFileChooser();

        fileChoise.setVisible(true);
        fileChoise.showOpenDialog(this);
        File file = fileChoise.getSelectedFile();
        if (file == null) {
            return;
        }
        if (file.length() > 1024 * 1024) {
            JOptionPane.showMessageDialog(null, "file anh qua lon");
            return;
        }
        try {
            BufferedImage biold = ImageIO.read(file);
            BufferedImage bi = new BufferedImage(lblPhoto.getSize().height, lblPhoto.getSize().width, BufferedImage.TYPE_INT_RGB);
            Graphics2D grap = bi.createGraphics();
            grap.drawImage(biold, 0, 0, lblPhoto.getSize().width, lblPhoto.getSize().height, null);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bi, "jpg", baos);
            dataImages = baos.toByteArray();
            showImage();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Khong luu duoc anh");
            return;
        }
    }
      
      
      private Icon icon;

    public void showImage() {
        if (dataImages == null) {
            lblPhoto.setText("Anh");
            lblPhoto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
            icon = new ImageIcon();
            lblPhoto.setIcon(icon);
            lblPhoto.setVisible(true);
        } else {
            lblPhoto.setText("");
            lblPhoto.setBorder(null);
            icon = new ImageIcon(dataImages);
            lblPhoto.setIcon(icon);
            lblPhoto.setVisible(true);
        }
    }
    
}
