
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import org.jdesktop.swingx.decorator.*;
import vn.com.dva.entities.GroupUser;
import vn.com.dva.entities.Users;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pnl_TaiKhoan.java
 *
 * Created on Aug 31, 2011, 11:52:20 PM
 */

/**
 *
 * @author VietAnh
 */
public class Pnl_TaiKhoan extends javax.swing.JPanel {

    private byte[] dataImages;
    private byte[] dataImagesU ;
    
    public byte[] getDataImages() {
        return dataImages;
    }
    public byte[] getDataImagesU() {
        return dataImagesU;
    }
    
    /** Creates new form Pnl_TaiKhoan */
    public Pnl_TaiKhoan() {
        initComponents();
        loadPanel();
        jTTaiKhoan.getModel().addTableModelListener(new TableModelListener() {

            public void tableChanged(TableModelEvent e) {
                JOptionPane.showMessageDialog(null, "Changed");
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTTaiKhoan = new org.jdesktop.swingx.JXTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jCbDSNhom = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        txtDSTenDangNhap = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDSHoTen = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        lblDoManh = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCbNhom = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        cbx = new javax.swing.JCheckBox();
        lbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jCbCity = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblCheck = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jCbCauHoi = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        txtTraLoi = new javax.swing.JTextField();
        lblCauHoi = new javax.swing.JLabel();
        txtCauHoi = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblCheck1 = new javax.swing.JLabel();
        jCbNhomU = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        btnHuy1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        cbx1 = new javax.swing.JCheckBox();
        txtUsernameU = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        passU = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        pass2U = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtHoTenU = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDiaChiU = new javax.swing.JTextField();
        jDateU = new com.toedter.calendar.JDateChooser();
        txtEmailU = new javax.swing.JTextField();
        txtDienThoaiU = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jCbCityU = new javax.swing.JComboBox();
        lblDoManh1 = new javax.swing.JLabel();
        lblPhotoU = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtCauHoiU = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtTraLoiU = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtIDU = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1100, 650));

        jTTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTTaiKhoanMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTTaiKhoan);

        jLabel19.setText("Quyền Hạn");

        jCbDSNhom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbDSNhomItemStateChanged(evt);
            }
        });

        jLabel20.setText("Tên Đăng Nhập");

        txtDSTenDangNhap.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDSTenDangNhapCaretUpdate(evt);
            }
        });

        jLabel21.setText("Họ Tên");

        txtDSHoTen.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDSHoTenCaretUpdate(evt);
            }
        });

        jButton2.setText("Làm Lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDSHoTen)
                            .addComponent(jCbDSNhom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDSTenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton2)))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jCbDSNhom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtDSTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtDSHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(jButton2)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sách", new javax.swing.ImageIcon(getClass().getResource("/resource/Filter.png")), jPanel1); // NOI18N

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 304));

        jLabel2.setText("Mật khẩu");

        jLabel3.setText("Nhập lại mật khẩu");

        pass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                passCaretUpdate(evt);
            }
        });

        lblDoManh.setForeground(new java.awt.Color(51, 102, 255));
        lblDoManh.setText("Yếu");

        pass2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pass2CaretUpdate(evt);
            }
        });

        jLabel1.setText("Tên đăng nhập");

        jLabel4.setText("Nhóm");

        jButton1.setText("Kiểm tra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbx.setText("Kích hoạt");

        lbl.setText("ok");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin cá nhân"));

        jLabel7.setText("Họ tên");

        jLabel8.setText("Ngày Sinh");

        jLabel9.setText("Địa chỉ");

        jLabel6.setText("Thành Phố");

        jLabel25.setText("Email");

        jLabel26.setText("Điện Thoại");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addComponent(jLabel6))
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDienThoai)
                    .addComponent(txtEmail)
                    .addComponent(jCbCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDiaChi)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnHuy.setText("Làm Lại");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        lblCheck.setText("jLabel5");

        jLabel23.setText("Câu Hỏi Bí Mật");

        jCbCauHoi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbCauHoiItemStateChanged(evt);
            }
        });

        jLabel24.setText("Trả Lời");

        lblCauHoi.setText("Câu Hỏi");

        lblPhoto.setBackground(new java.awt.Color(102, 102, 102));
        lblPhoto.setText("jLabel10");
        lblPhoto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lblPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhotoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnThem)
                        .addGap(11, 11, 11)
                        .addComponent(btnHuy))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel23)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblCauHoi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblDoManh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTraLoi, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCbNhom, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jCbCauHoi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCauHoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem)
                            .addComponent(btnHuy)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel23)
                                .addGap(6, 6, 6)
                                .addComponent(lblCauHoi)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel24)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))
                                .addGap(7, 7, 7)
                                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDoManh))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCheck))
                                .addGap(10, 10, 10)
                                .addComponent(jCbCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(txtTraLoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCbNhom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbx)))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thêm Mới", new javax.swing.ImageIcon(getClass().getResource("/resource/Add.png")), jPanel2); // NOI18N

        jLabel5.setText("Nhóm Người Dùng");

        lblCheck1.setText("jLabel5");

        jLabel11.setText("Tên đăng nhập");

        btnHuy1.setText("Hủy Bỏ");
        btnHuy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuy1ActionPerformed(evt);
            }
        });

        btnUpdate.setText("Cập Nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        cbx1.setText("Kích hoạt");

        txtUsernameU.setEnabled(false);

        jLabel12.setText("Độ mạnh :");

        jLabel13.setText("Mật khẩu");

        passU.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                passUCaretUpdate(evt);
            }
        });
        passU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passUKeyPressed(evt);
            }
        });

        jLabel14.setText("Nhập lại mật khẩu");

        pass2U.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pass2UCaretUpdate(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin cá nhân"));

        jLabel15.setText("Họ tên");

        jLabel16.setText("Ngày Sinh");

        jLabel17.setText("Địa chỉ");

        jLabel10.setText("Email");

        jLabel18.setText("Thành Phố");

        jLabel27.setText("Điện Thoại");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDienThoaiU)
                    .addComponent(jCbCityU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmailU)
                    .addComponent(txtDiaChiU)
                    .addComponent(jDateU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHoTenU, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTenU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jDateU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChiU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtEmailU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jCbCityU, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDienThoaiU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        lblDoManh1.setForeground(new java.awt.Color(51, 102, 255));
        lblDoManh1.setText("Yếu");

        lblPhotoU.setBackground(new java.awt.Color(102, 102, 102));
        lblPhotoU.setText("jLabel10");
        lblPhotoU.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lblPhotoU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhotoUMouseClicked(evt);
            }
        });

        jLabel28.setText("Câu Hỏi Bí Mật");

        txtCauHoiU.setEnabled(false);

        jLabel29.setText("Trả Lời");

        txtTraLoiU.setEnabled(false);

        jLabel30.setText("Mã người dùng");

        txtIDU.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnUpdate)
                        .addGap(10, 10, 10)
                        .addComponent(btnHuy1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPhotoU, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel5)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbx1)
                    .addComponent(txtCauHoiU)
                    .addComponent(jCbNhomU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pass2U)
                    .addComponent(passU)
                    .addComponent(txtUsernameU)
                    .addComponent(txtIDU, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(txtTraLoiU))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDoManh1))
                    .addComponent(lblCheck1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblPhotoU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate)
                            .addComponent(btnHuy1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6)
                                .addComponent(lblDoManh1)
                                .addGap(14, 14, 14)
                                .addComponent(lblCheck1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtIDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtUsernameU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(passU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(pass2U, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jCbNhomU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(cbx1)
                                .addGap(7, 7, 7)
                                .addComponent(txtCauHoiU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTraLoiU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel11)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel13)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel14)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel28)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel29))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Cập Nhật", new javax.swing.ImageIcon(getClass().getResource("/resource/Edit.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            if (Cl_Client.c.checkUser(txtUsername.getText()) && txtUsername.getText().length() >=4) {
                lbl.setForeground(Color.BLUE);
                lbl.setText("Có thể sử dụng");
            } else {
                lbl.setForeground(Color.RED);
                lbl.setText("Đã tồn tại!!!");
            }

        } catch (RemoteException ex) {
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // TODO add your handling code here:
            try {
                if (!Cl_Client.c.checkUser(txtUsername.getText()) || txtUsername.getText().length() <= 3) {
                    Cl_Client.ShowError("Đã tồn tại tên đăng nhập ! Vui lòng chọn tên khác");
                    return ;
                }
                } catch (RemoteException ex) {
                    Logger.getLogger(Pnl_CauHoi.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (txtUsername.getText().equals("") || pass.getText().equals("")|| pass2.getText().equals("") || txtHoTen.getText().equals("")) {
                    Cl_Client.ShowError("Hãy nhập đầy đủ thông tin !");
                    return;
                }
                if (!pass.getText().equals(pass2.getText())) {
                    Cl_Client.ShowError("Sai password rồi !");
                    return;
                }

                if (jCbNhom.getSelectedIndex() == 0 ) {
                    Cl_Client.ShowError("Bạn phải chọn nhóm người dùng");
                    return;
                }
                if (jCbCauHoi.getSelectedIndex()== 0) {
                    Cl_Client.ShowError("Bạn phải chọn 1 câu hỏi bí mật !!!");
                    return;
                }

                if (jCbCauHoi.getSelectedIndex() == 7 && txtCauHoi.getText().equals(""))
                {
                    Cl_Client.ShowError("Bạn hãy nhập nội dung câu hỏi !!!");
                    return;
                }

                if (txtTraLoi.getText().equals(""))
                {
                    Cl_Client.ShowError(" Hãy nhập câu trả lời !!!");
                    return;
                }
                if (txtTraLoi.getText().length() < 2)
                {
                    Cl_Client.ShowError(" Câu trả lời có ít nhất 2 ký tự!!!");
                    return;
                }


                String cauhoi ="";
                if (jCbCauHoi.getSelectedIndex() != 7 )
                    cauhoi = jCbCauHoi.getSelectedItem().toString();
                else
                    cauhoi = txtCauHoi.getText();

                String traloi = txtTraLoi.getText();
                
                
                String fullName = txtHoTen.getText();
                String address = txtDiaChi.getText();
                String city ="";
                if (jCbCity.getSelectedIndex() != 0) {
                    city = jCbCity.getSelectedItem().toString();
                }
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                String birthday = sdf.format(jDate.getDate());
                String email = txtEmail.getText();
                String phone = txtDienThoai.getText();
                boolean enable ;
                if (cbx.isSelected()) enable = true; 
                else enable = false ;
                byte[] image = getDataImages();
                Date d = new Date();
                String dateJoint = sdf.format(d);
                Long idGroup = ((GroupUser)jCbNhom.getSelectedItem()).getGroupID();
                Users u = new Users(txtUsername.getText().trim(), pass.getText(), idGroup , fullName , birthday  , address , city , 
                    email , phone , image , dateJoint , dateJoint , enable ,cauhoi ,traloi);
                if (Cl_Client.c.insertUser(u)){
                    resetAll();
                    loadTable();
                }
                else JOptionPane.showMessageDialog(null, "Them loi");
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_TaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
            
}//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        resetAll();
        loadTable();
        
}//GEN-LAST:event_btnHuyActionPerformed

    private void btnHuy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuy1ActionPerformed
        // TODO add your handling code here:
        resetAllCapNhat();
        loadTable();
    }//GEN-LAST:event_btnHuy1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            if (jTTaiKhoan.getSelectedColumn() == -1)
            {
                JOptionPane.showConfirmDialog(null, "Vui lòng chọn 1 hàng ở dưới","Lỗi",JOptionPane.OK_OPTION,JOptionPane.ERROR_MESSAGE );
                return ;
            }
            

            if ( passU.getText().equals("")|| pass2U.getText().equals("") || txtHoTenU.getText().equals("")) {
                Cl_Client.ShowError("Hãy nhập đầy đủ thông tin !");
                return;
            }
            if (!passU.getText().equals(pass2U.getText())) {
                Cl_Client.ShowError("Sai password rồi !");
                return;
            }

            if (jCbNhomU.getSelectedIndex() == 0 ) {
                Cl_Client.ShowError("Bạn phải chọn nhóm người dùng");
                return;
            }

            boolean enable = false;
            if (cbx1.isSelected()) {
                enable = true;
            }

            Long idUser = Long.parseLong(txtIDU.getText());
            Users u = Cl_Client.c.getUserByID(idUser);
            String password = passU.getText();
            GroupUser g = (GroupUser) jCbNhomU.getSelectedItem();
            String hoten = txtHoTenU.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String date = sdf.format(jDateU.getDate());
            String dc = txtDiaChiU.getText();
            String email = txtEmailU.getText();
            String city = jCbCityU.getSelectedItem().toString();
            String phone = txtDienThoaiU.getText();
            byte[] image = getDataImagesU();
            
            Date d = new Date();
            String dateUpdate = sdf.format(d);
            
            
            Users bean = new Users(u.getUserID(),u.getUserName(), g.getGroupID(),password , hoten , date  , dc , city , 
                    email , phone , image , u.getJoinDate() ,dateUpdate , enable ,u.getQuestion() , u.getAnserQuestion());
            
            if (Cl_Client.c.updateUser(bean)) {
                resetAll();
                loadTable();
            } else {
                Cl_Client.ShowError("Update lỗi rồi");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_TaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void passUKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passUKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passUKeyPressed

    private void jTTaiKhoanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTaiKhoanMouseReleased
        // TODO add your handling code here:
        Long id ;
        try {
            id = Main.client.getIDTable(jTTaiKhoan);
        } catch (Exception ex) {
            id=1L;
        }
        
        if (!id.equals(""))
        {
            try {
                Users u = Cl_Client.c.getUserByID(id);
                
                GroupUser g = Cl_Client.c.getGroupByID(u.getGroupUserID());
                String dateString = u.getBirthday();
                String s[] = dateString.split("-");
                int year = Integer.parseInt(s[2])-1900;
                int month = Integer.parseInt(s[1])- 1;
                int date = Integer.parseInt(s[0]);
                Date d = new Date(year, month, date);
                
                txtIDU.setText(""+u.getUserID());
                txtUsernameU.setText(u.getUserName());
                passU.setText(u.getPassword());
                pass2U.setText(u.getPassword());
                
                int index = 0 ;
                for (int i=1;i<jCbNhomU.getItemCount();i++) {
                    GroupUser gu = (GroupUser)jCbNhomU.getItemAt(i);
                    if (gu.getGroupID().equals(g.getGroupID())) index = i;
                }
                jCbNhomU.setSelectedIndex(index);

                if (u.getEnable()) cbx1.setSelected(true);
                else cbx1.setSelected(false);
                txtCauHoiU.setText(u.getQuestion());
                txtTraLoiU.setText(u.getAnserQuestion());
                txtHoTenU.setText(u.getFullName());
                jDateU.setDateFormatString("dd-MM-yyyy");
                jDateU.setDate(d);
                txtDiaChiU.setText(u.getAddress());
                txtEmailU.setText(u.getEmail());
                jCbCityU.setSelectedItem(u.getCity());
                txtDienThoaiU.setText(u.getMobile());
                dataImagesU = u.getPhoto();
                showImageUpdate();
                
                
            } catch (RemoteException ex) {
                Logger.getLogger(Pnl_TaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTTaiKhoanMouseReleased

    private void txtDSTenDangNhapCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDSTenDangNhapCaretUpdate
        // TODO add your handling code here:
        String qh = jCbDSNhom.getSelectedItem().toString();
        
        if (qh.equals("--  Tất Cả  --")) qh = "";
            jTTaiKhoan.setFilters(new FilterPipeline(
                    new Filter[] { new PatternFilter(qh+".*", 0, 4), new PatternFilter(txtDSTenDangNhap.getText() +".*", 0, 1), new PatternFilter(txtDSHoTen.getText().toString()+".*", 0, 2) }));

    }//GEN-LAST:event_txtDSTenDangNhapCaretUpdate

    private void txtDSHoTenCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDSHoTenCaretUpdate
        // TODO add your handling code here:
        String qh = jCbDSNhom.getSelectedItem().toString();

        if (qh.equals("--  Tất Cả  --")) qh = "";
            jTTaiKhoan.setFilters(new FilterPipeline(
                    new Filter[] { new PatternFilter(qh+".*", 0, 4), new PatternFilter(txtDSTenDangNhap.getText() +".*", 0, 1), new PatternFilter(txtDSHoTen.getText().toString()+".*", 0, 2) }));

    }//GEN-LAST:event_txtDSHoTenCaretUpdate

    private void jCbDSNhomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbDSNhomItemStateChanged
        // TODO add your handling code here:
        String qh = evt.getItem().toString();

        if (qh.equals("--  Tất Cả  --")) qh = "";
        jTTaiKhoan.setFilters(new FilterPipeline(
             new Filter[] { new PatternFilter(qh+".*", 0, 4), new PatternFilter(txtDSTenDangNhap.getText() +".*", 0, 1), new PatternFilter(txtDSHoTen.getText().toString()+".*", 0, 2) }));

    }//GEN-LAST:event_jCbDSNhomItemStateChanged

    private void passCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_passCaretUpdate
        // TODO add your handling code here:
        if (pass.getText().length() <5) {
            lblDoManh.setForeground(new java.awt.Color(51, 102, 255));
            lblDoManh.setText("Yếu");
        }

        if (pass.getText().length() >=5 && pass.getText().length() <= 7 ) {
            lblDoManh.setForeground(Color.BLUE);
            lblDoManh.setText("Trung Bình");
        }
        if (pass.getText().length() >=8) {
            lblDoManh.setForeground(Color.RED);
            lblDoManh.setText("Mạnh");
        }
    }//GEN-LAST:event_passCaretUpdate

    private void pass2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pass2CaretUpdate
        // TODO add your handling code here:
        if (pass.getText().equals(pass2.getText())) {
            lblCheck.setText("OK");
        } else lblCheck.setText("Sai");
    }//GEN-LAST:event_pass2CaretUpdate

    private void passUCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_passUCaretUpdate
        // TODO add your handling code here:
        if (passU.getText().length() <5) {
            lblDoManh1.setForeground(new java.awt.Color(51, 102, 255));
            lblDoManh1.setText("Yếu");
        }

        if (passU.getText().length() >=5 && pass.getText().length() <= 7 ) {
            lblDoManh1.setForeground(Color.BLUE);
            lblDoManh1.setText("Trung Bình");
        }
        if (passU.getText().length() >=8) {
            lblDoManh1.setForeground(Color.RED);
            lblDoManh1.setText("Mạnh");
        }
    }//GEN-LAST:event_passUCaretUpdate

    private void pass2UCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pass2UCaretUpdate
        // TODO add your handling code here:
        if (passU.getText().equals(pass2U.getText())) {
            lblCheck1.setText("OK");
        } else lblCheck1.setText("Sai");
    }//GEN-LAST:event_pass2UCaretUpdate

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jCbDSNhom.setSelectedIndex(0);
        txtDSTenDangNhap.setText("");
        txtDSHoTen.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCbCauHoiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbCauHoiItemStateChanged
        // TODO add your handling code here:
        int id = jCbCauHoi.getSelectedIndex();

        if (id == 7)
        {
            lblCauHoi.setVisible(true);
            txtCauHoi.setVisible(true);
        }
        else
        {
            lblCauHoi.setVisible(false);
            txtCauHoi.setVisible(false);
        }
    }//GEN-LAST:event_jCbCauHoiItemStateChanged

private void lblPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhotoMouseClicked
// TODO add your handling code here:
    if (evt.getClickCount() == 2) {
        loadImage();
    }
}//GEN-LAST:event_lblPhotoMouseClicked

private void lblPhotoUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhotoUMouseClicked
// TODO add your handling code here:
    if (evt.getClickCount() == 2) {
        loadImageU();
    }
}//GEN-LAST:event_lblPhotoUMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnHuy1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox cbx;
    private javax.swing.JCheckBox cbx1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCbCauHoi;
    private javax.swing.JComboBox jCbCity;
    private javax.swing.JComboBox jCbCityU;
    private javax.swing.JComboBox jCbDSNhom;
    private javax.swing.JComboBox jCbNhom;
    private javax.swing.JComboBox jCbNhomU;
    private com.toedter.calendar.JDateChooser jDate;
    private com.toedter.calendar.JDateChooser jDateU;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable jTTaiKhoan;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblCauHoi;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblCheck1;
    private javax.swing.JLabel lblDoManh;
    private javax.swing.JLabel lblDoManh1;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPhotoU;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JPasswordField pass2U;
    private javax.swing.JPasswordField passU;
    private javax.swing.JTextField txtCauHoi;
    private javax.swing.JTextField txtCauHoiU;
    private javax.swing.JTextField txtDSHoTen;
    private javax.swing.JTextField txtDSTenDangNhap;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiaChiU;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtDienThoaiU;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailU;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHoTenU;
    private javax.swing.JTextField txtIDU;
    private javax.swing.JTextField txtTraLoi;
    private javax.swing.JTextField txtTraLoiU;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsernameU;
    // End of variables declaration//GEN-END:variables

    private void resetAll() {
       txtUsername.setText("");
       pass.setText("");
       pass2.setText("");
       txtHoTen.setText("");
       
       txtDiaChi.setText("");
       lbl.setText("");
       lblDoManh.setText("Điền mật khẩu");
       lblCheck.setText("Sai");
       
       jCbCauHoi.setSelectedIndex(0);
       txtTraLoi.setText("");
       txtCauHoi.setText("");
       
       jCbNhom.setSelectedIndex(0);
       
       txtHoTen.setText("");
       txtDiaChi.setText("");
       jCbCity.setSelectedIndex(0);
       
       txtEmail.setText("");
       txtDiaChi.setText("");
       txtDienThoai.setText("");
       
       jDate.setDate(null);
       dataImages = null ;
       showImage();
    }

    private void resetAllCapNhat() {
       txtUsernameU.setText("");
       passU.setText("");
       pass2U.setText("");
       txtHoTenU.setText("");

       txtDiaChiU.setText("");
       cbx.setSelected(false);
    }

    private void loadTable()
    {
        try {
            jTTaiKhoan.setModel(Cl_Client.c.getAllUserToTable());
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_KyThi.class.getName()).log(Level.SEVERE, null, ex);
        }
            HighlighterPipeline highlighters = new HighlighterPipeline();
            highlighters.addHighlighter(new AlternateRowHighlighter().linePrinter);
            jTTaiKhoan.setHighlighters(highlighters);
    }

    private void loadPanel() {
        try {
            // Tao table co so du lieu
            
            jTTaiKhoan.setModel(Cl_Client.c.getAllUserToTable());
            HighlighterPipeline highlighters = new HighlighterPipeline();
            highlighters.addHighlighter(new AlternateRowHighlighter().linePrinter);
            jTTaiKhoan.setHighlighters(highlighters);
                
                
            List<GroupUser> list = Cl_Client.c.getAllGroup();
            jCbNhom.addItem("---  Chọn 1 ---");
            jCbNhomU.addItem("---  Chọn 1 ---");
            jCbDSNhom.addItem("--  Tất Cả  --");
            for (GroupUser g : list){
                jCbNhom.addItem(g);
                jCbNhomU.addItem(g);
                jCbDSNhom.addItem(g);
            }
            

            jCbCity.addItem("Lựa Chọn");
            jCbCity.addItem("Hà Nội");
            jCbCity.addItem("TP. Hồ Chí Minh");
            jCbCity.addItem("Huế");
            jCbCity.addItem("Đà Nẵng");
            jCbCity.addItem("Hải Phòng");
            jCbCity.addItem("Bắc Giang");
            
            jCbCityU.addItem("Lựa Chọn");
            jCbCityU.addItem("Hà Nội");
            jCbCityU.addItem("TP. Hồ Chí Minh");
            jCbCityU.addItem("Huế");
            jCbCityU.addItem("Đà Nẵng");
            jCbCityU.addItem("Hải Phòng");
            jCbCityU.addItem("Bắc Giang");
            

            // Câu Hỏi bí mật
            jCbCauHoi.removeAllItems();
            jCbCauHoi.addItem("Chọn một?");
            jCbCauHoi.addItem("Cha của bạn sinh ra ở thành phố nào ?");
            jCbCauHoi.addItem("Tên trường tiểu học của bạn là gì ?");
            jCbCauHoi.addItem("Con vật cưng đầu tiên của bạn tên gì ?");
            jCbCauHoi.addItem("Nhân vật trong phim mà bạn thích nhất là ai ?");
            jCbCauHoi.addItem("Tên nhạc sĩ bạn thích nhất ?");
            jCbCauHoi.addItem("Món khoái khẩu lúc bạn còn nhỏ là gì ?");
            jCbCauHoi.addItem("-- Nhập câu hỏi của bạn tại đây --");

            lblCauHoi.setVisible(false);
            txtCauHoi.setVisible(false);


            // Ngày tháng năm
            

        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_TaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

/////////////////////////////////   Xu ly Image  /////////////////////////////////
    private void loadImage() {
        JFileChooser fileChoise = new JFileChooser();

        fileChoise.setVisible(true);
        fileChoise.showOpenDialog(this);
        File file = fileChoise.getSelectedFile();
        if (file == null) {
            return;
        }
        if (file.length() > 1024 * 1024) {
            JOptionPane.showMessageDialog(null, "file anh qua lon");
            return;
        }
        try {
            BufferedImage biold = ImageIO.read(file);
            BufferedImage bi = new BufferedImage(lblPhoto.getSize().height, lblPhoto.getSize().width, BufferedImage.TYPE_INT_RGB);
            Graphics2D grap = bi.createGraphics();
            grap.drawImage(biold, 0, 0, lblPhoto.getSize().width, lblPhoto.getSize().height, null);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bi, "jpg", baos);
            dataImages = baos.toByteArray();
            showImage();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Khong luu duoc anh");
            return;
        }
    }
    
    
    
    
    private void loadImageU() {
        JFileChooser fileChoise = new JFileChooser();

        fileChoise.setVisible(true);
        fileChoise.showOpenDialog(this);
        File file = fileChoise.getSelectedFile();
        if (file == null) {
            return;
        }
        if (file.length() > 1024 * 1024) {
            JOptionPane.showMessageDialog(null, "file anh qua lon");
            return;
        }
        try {
            BufferedImage biold = ImageIO.read(file);
            BufferedImage bi = new BufferedImage(lblPhotoU.getSize().height, lblPhotoU.getSize().width, BufferedImage.TYPE_INT_RGB);
            Graphics2D grap = bi.createGraphics();
            grap.drawImage(biold, 0, 0, lblPhotoU.getSize().width, lblPhotoU.getSize().height, null);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bi, "jpg", baos);
            dataImagesU = baos.toByteArray();
            showImage();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Khong luu duoc anh");
            return;
        }
    }
    
    
    private Icon icon;

    public void showImage() {
        if (dataImages == null) {
            lblPhoto.setText("Anh");
            lblPhoto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
            icon = new ImageIcon();
            lblPhoto.setIcon(icon);
            lblPhoto.setVisible(true);
        } else {
            lblPhoto.setText("");
            lblPhoto.setBorder(null);
            icon = new ImageIcon(dataImages);
            lblPhoto.setIcon(icon);
            lblPhoto.setVisible(true);
        }
    }
    
    public void showImageUpdate() {
        if (dataImagesU == null) {
            lblPhotoU.setText("Anh");
            lblPhotoU.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
            icon = new ImageIcon();
            lblPhotoU.setIcon(icon);
            lblPhotoU.setVisible(true);
        } else {
            lblPhotoU.setText("");
            lblPhotoU.setBorder(null);
            icon = new ImageIcon(dataImagesU);
            lblPhotoU.setIcon(icon);
            lblPhotoU.setVisible(true);
        }

    }

    public void setDataImages(byte[] dataImages) {
        this.dataImages = dataImages;
    }
    
    
}
