
import java.rmi.RemoteException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.decorator.*;
import vn.com.dva.entities.Exam;
import vn.com.dva.entities.LevelAll;
import vn.com.dva.entities.Subject;
import vn.com.dva.entities.Users;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pnl_KyThi.java
 *
 * Created on Aug 28, 2011, 3:14:47 PM
 */
/**
 *
 * @author VietAnh
 */
public class Pnl_KyThi extends javax.swing.JPanel {

    /** Creates new form Pnl_KyThi */
    public Pnl_KyThi() {
        initComponents();
        loadPanel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtIdKyThi = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDSTenKyThi = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtDSMonThi = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenKyThi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCbDoKho = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblKho = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblDe = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTb = new javax.swing.JLabel();
        jCbMonThi = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtThoiGianLamBai = new javax.swing.JTextField();
        jCbSoLuotLam = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dateStart = new com.toedter.calendar.JDateChooser();
        dateEnd = new com.toedter.calendar.JDateChooser();
        chk = new javax.swing.JCheckBox();
        txtSoCauHoi = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTenKyThiE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCbDoKhoE = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblKho1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblDe1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTb1 = new javax.swing.JLabel();
        jCbMonThiE = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        txtThoiGianLamBaiE = new javax.swing.JTextField();
        jCbSoLuotLamE = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        dateStartU = new com.toedter.calendar.JDateChooser();
        dateEndU = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jCbXoa = new javax.swing.JButton();
        txtSoCauHoiU = new javax.swing.JTextField();
        chkU = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTKyThi = new org.jdesktop.swingx.JXTable();

        jPanel2.setPreferredSize(new java.awt.Dimension(1100, 650));

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseReleased(evt);
            }
        });

        jLabel20.setText("ID Kỳ Thi");

        txtIdKyThi.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtIdKyThiCaretUpdate(evt);
            }
        });

        jLabel21.setText("Tên Kỳ Thi");

        txtDSTenKyThi.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDSTenKyThiCaretUpdate(evt);
            }
        });

        jLabel22.setText("Môn Thi");

        txtDSMonThi.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDSMonThiCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDSMonThi)
                    .addComponent(txtDSTenKyThi)
                    .addComponent(txtIdKyThi, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addContainerGap(526, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtIdKyThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(txtDSTenKyThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtDSMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Danh Sách", new javax.swing.ImageIcon(getClass().getResource("/resource/Filter.png")), jPanel6); // NOI18N

        jLabel2.setText("Tên Kỳ Thi");

        jLabel3.setText("Độ Khó");

        jCbDoKho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCbDoKho.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbDoKhoItemStateChanged(evt);
            }
        });

        jButton2.setText("Làm Lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Thời gian bắt đầu");

        lblKho.setText("Khó");

        jLabel5.setText("Thời gian kết thúc");

        jButton1.setText("Thêm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Môn Thi");

        lblDe.setText("Dễ");

        jLabel7.setText("Thời gian làm bài");

        lblTb.setText("TB");

        jCbMonThi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Phút");

        jCbSoLuotLam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("Số lượt được làm");

        jLabel1.setText("Khó");

        jLabel15.setText("Trung Bình");

        jLabel19.setText("Dễ");

        chk.setText("Xác định mặc định số câu hỏi");
        chk.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(71, 71, 71))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblKho)
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(lblTb)
                                                .addGap(15, 15, 15)
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblDe))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtThoiGianLamBai, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtSoCauHoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8)))
                                        .addGap(45, 45, 45))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jCbDoKho, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTenKyThi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel16))
                                .addGap(20, 20, 20))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateStart, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(dateEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCbMonThi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCbSoLuotLam, javax.swing.GroupLayout.Alignment.LEADING, 0, 105, Short.MAX_VALUE)))
                        .addGap(144, 144, 144))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(chk)
                        .addContainerGap(612, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenKyThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jCbDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKho)
                            .addComponent(jLabel1)
                            .addComponent(jLabel15)
                            .addComponent(lblTb)
                            .addComponent(jLabel19)
                            .addComponent(lblDe)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jCbSoLuotLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtThoiGianLamBai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jCbMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk)
                    .addComponent(txtSoCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Thêm Mới", new javax.swing.ImageIcon(getClass().getResource("/resource/Add.png")), jPanel5); // NOI18N

        jLabel9.setText("Tên Kỳ Thi");

        jLabel10.setText("Độ Khó");

        jCbDoKhoE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCbDoKhoE.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbDoKhoEItemStateChanged(evt);
            }
        });

        jButton3.setText("Hủy bỏ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Thời gian bắt đầu");

        lblKho1.setText("Khó");

        jLabel12.setText("Thời gian kết thúc");

        jButton4.setText("Cập Nhật");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setText("Môn Thi");

        lblDe1.setText("Dễ");

        jLabel14.setText("Thời gian làm bài");

        lblTb1.setText("Trung Bình");

        jCbMonThiE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setText("Phút");

        jCbSoLuotLamE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel18.setText("Số lượt được làm");

        jLabel23.setText("Người Tạo");

        jLabel24.setText("Số Lượt Đã Làm");

        txtUserName.setEnabled(false);

        txtTotal.setText("0");
        txtTotal.setEnabled(false);

        jCbXoa.setText("Xóa");
        jCbXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbXoaActionPerformed(evt);
            }
        });

        chkU.setText("Xác định mặc định số câu hỏi");
        chkU.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkUStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenKyThiE, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(jCbDoKhoE, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(lblKho1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTb1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDe1)))
                        .addGap(90, 90, 90))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(72, 72, 72)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtThoiGianLamBaiE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(chkU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoCauHoiU)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCbXoa))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel24))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal)
                            .addComponent(dateStartU, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(dateEndU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCbMonThiE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCbSoLuotLamE, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(158, 158, 158))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(txtThoiGianLamBaiE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(dateStartU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(dateEndU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jCbSoLuotLamE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jCbMonThiE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4)
                                    .addComponent(jButton3)
                                    .addComponent(jCbXoa)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtTenKyThiE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jCbDoKhoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblKho1)
                                    .addComponent(lblTb1)
                                    .addComponent(lblDe1))
                                .addGap(107, 107, 107)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chkU)
                                    .addComponent(txtSoCauHoiU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cập Nhật", new javax.swing.ImageIcon(getClass().getResource("/resource/Edit.png")), jPanel4); // NOI18N

        jTKyThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTKyThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTKyThiMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTKyThi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2MouseReleased

    private void jTKyThiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTKyThiMouseReleased
        // TODO add your handling code here:
        Long id = Main.client.getIDTable(jTKyThi);
        if (!id.equals("") || id != -1) {
            try {
                Exam bean = Cl_Client.c.getExamByID(id);
                LevelAll level = Cl_Client.c.getLeveltByID(bean.getLevelID());
                Subject subject = Cl_Client.c.getSubjectByID(bean.getSubjectID());
                Users user = Cl_Client.c.getUserByID(bean.getUserID());

                txtTenKyThiE.setText(bean.getExamName());
                jCbDoKhoE.getModel().setSelectedItem(level);
                jCbMonThiE.getModel().setSelectedItem(subject);
                txtThoiGianLamBaiE.setText(bean.getTimes() + "");
                txtUserName.setText(user.getUserName());
                jCbSoLuotLamE.setSelectedItem(bean.getNumberOfTest() + "");
                txtTotal.setText(bean.getTotalOfTest() + "");
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                Calendar c1 = bean.getDateStart();
                Calendar c2 = bean.getDateEnd();
                dateStartU.setDateFormatString("dd-MM-yyyy");
                dateStartU.setCalendar(c1);

                dateEndU.setDateFormatString("dd-MM-yyyy");
                dateEndU.setCalendar(c2);

            } catch (RemoteException ex) {
                Logger.getLogger(Pnl_KyThi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
}//GEN-LAST:event_jTKyThiMouseReleased

    private void jCbDoKhoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbDoKhoItemStateChanged
        if (jCbDoKho.getSelectedIndex() > 0) {
            LevelAll level = (LevelAll) jCbDoKho.getSelectedItem();
            lblKho.setText(level.getPercentHard() + "");
            lblTb.setText(level.getPercentNormal() + "");
            lblDe.setText(level.getPercentEasy() + "");
        }
}//GEN-LAST:event_jCbDoKhoItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        resetThemMoi();

}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            if (txtTenKyThi.getText().length() <= 0) {
                return;
            }
            if (jCbDoKho.getSelectedIndex() == 0 || jCbMonThi.getSelectedIndex() == 0) {
                return;
            }
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

            Date d1 = dateStart.getDate();
            Date d2 = dateEnd.getDate();
            String s = sdf.format(d1);
            Date ds = new Date();
            Date de = new Date();
            try {
                ds = sdf.parse(s);
                de = sdf.parse(sdf.format(d2));
            } catch (ParseException ex) {
            }

            Calendar c1 = Calendar.getInstance();
            Calendar c2 = Calendar.getInstance();
            c1.setTime(ds);
            c2.setTime(de);

            LevelAll level = (LevelAll) jCbDoKho.getSelectedItem();
            String userName = User.username;
            Users user = Cl_Client.c.getUserByUserName(userName);
            Subject subject = (Subject) jCbMonThi.getSelectedItem();
            int tg = Integer.parseInt(txtThoiGianLamBai.getText());
            int sl = Integer.parseInt(jCbSoLuotLam.getSelectedItem().toString().trim());
            int socauhoi = 0;
            if (chk.isSelected()) socauhoi = Integer.parseInt(txtSoCauHoi.getText().trim());
            Exam bean = new Exam(txtTenKyThi.getText(), level.getLevelAllID(), user.getUserID(), subject.getSubjecId(), c1, c2, tg, sl, 0, socauhoi);
            if (Cl_Client.c.insertExam(bean)) {
                resetThemMoi();
            } else {
                JOptionPane.showMessageDialog(null, "Lỗi");
            }
            loadPanel();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nhập sai ngày tháng");
            resetThemMoi();
            loadPanel();
            return;
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jCbDoKhoEItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbDoKhoEItemStateChanged
        // TODO add your handling code here:
        if (jCbDoKhoE.getSelectedIndex() > 0) {
            LevelAll level = (LevelAll) jCbDoKhoE.getSelectedItem();
            lblKho1.setText(level.getPercentHard() + "");
            lblTb1.setText(level.getPercentNormal() + "");
            lblDe1.setText(level.getPercentEasy() + "");
        }
    }//GEN-LAST:event_jCbDoKhoEItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Long id = Main.client.getIDTable(jTKyThi);
        if (!id.equals("") || id != -1) {
            try {

                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

                Date d1 = dateStartU.getDate();
                Date d2 = dateEndU.getDate();
                String s = sdf.format(d1);
                Date ds = new Date();
                Date de = new Date();
                try {
                    ds = sdf.parse(s);
                    de = sdf.parse(sdf.format(d2));
                } catch (ParseException ex) {
                }
                Calendar c1 = Calendar.getInstance();
                Calendar c2 = Calendar.getInstance();
                c1.setTime(ds);
                c2.setTime(de);

                if (txtTenKyThiE.getText().length() <= 0) {
                    return;
                }
                if (jCbDoKhoE.getSelectedIndex() == 0) {
                    return;
                }
                if (txtThoiGianLamBaiE.getText().length() <= 0) {
                    return;
                }
                if (jCbDoKhoE.getSelectedIndex() == 0) {
                    return;
                }
                if (jCbMonThiE.getSelectedIndex() == 0) {
                    return;
                }
                if (jCbSoLuotLamE.getSelectedIndex() == 0) {
                    return;
                }
                Exam bean = Cl_Client.c.getExamByID(id);
                Subject subject = (Subject) jCbMonThiE.getSelectedItem();
                LevelAll level = (LevelAll) jCbDoKhoE.getSelectedItem();
                int tg = Integer.parseInt(txtThoiGianLamBaiE.getText());
                int sl = Integer.parseInt(jCbSoLuotLamE.getSelectedItem().toString().trim());
                int socauhoi = 0;
                if (chkU.isSelected()) socauhoi = Integer.parseInt(txtSoCauHoiU.getText().trim());
                
                bean.setExamName(txtTenKyThiE.getText());
                bean.setLevelID(level.getLevelAllID());
                bean.setSubjectID(subject.getSubjecId());
                bean.setDateStart(c1);
                bean.setDateEnd(c2);
                bean.setTimes(tg);
                bean.setNumberOfTest(sl);
                bean.setNumberQuestion(socauhoi);
                
                if (Cl_Client.c.updateExam(bean)) {
                    resetThemMoi();
                    loadPanel();
                } else {
                    JOptionPane.showMessageDialog(null, " Lỗi ");
                }
            } catch (RemoteException ex) {
                Logger.getLogger(Pnl_KyThi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtIdKyThiCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtIdKyThiCaretUpdate
        // TODO add your handling code here:
        jTKyThi.setFilters(new FilterPipeline(
                new Filter[]{new PatternFilter(txtIdKyThi.getText() + ".*", 0, 0), new PatternFilter(txtDSTenKyThi.getText() + ".*", 0, 1), new PatternFilter(txtDSMonThi.getText() + ".*", 0, 3)}));
    }//GEN-LAST:event_txtIdKyThiCaretUpdate

    private void txtDSTenKyThiCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDSTenKyThiCaretUpdate
        // TODO add your handling code here:
        jTKyThi.setFilters(new FilterPipeline(
                new Filter[]{new PatternFilter(txtIdKyThi.getText() + ".*", 0, 0), new PatternFilter(txtDSTenKyThi.getText() + ".*", 0, 1), new PatternFilter(txtDSMonThi.getText() + ".*", 0, 3)}));

    }//GEN-LAST:event_txtDSTenKyThiCaretUpdate

    private void txtDSMonThiCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDSMonThiCaretUpdate
        // TODO add your handling code here:
        jTKyThi.setFilters(new FilterPipeline(
                new Filter[]{new PatternFilter(txtIdKyThi.getText() + ".*", 0, 0), new PatternFilter(txtDSTenKyThi.getText() + ".*", 0, 1), new PatternFilter(txtDSMonThi.getText() + ".*", 0, 3)}));

    }//GEN-LAST:event_txtDSMonThiCaretUpdate

private void jCbXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbXoaActionPerformed
// TODO add your handling code here:
    Long id = Main.client.getIDTable(jTKyThi);
    if (!id.equals("") || id != -1) {
        try {
            Cl_Client.c.removeExam(id);
            reset();
            loadPanel();
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_KyThi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}//GEN-LAST:event_jCbXoaActionPerformed

    private void chkUStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkUStateChanged
        // TODO add your handling code here:\
        if (chkU.isSelected()) txtSoCauHoiU.setVisible(true);
        else txtSoCauHoiU.setVisible(false);
    }//GEN-LAST:event_chkUStateChanged

    private void chkStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkStateChanged
        // TODO add your handling code here:
        if (chk.isSelected()) txtSoCauHoi.setVisible(true);
        else txtSoCauHoi.setVisible(false);
        this.repaint();
    }//GEN-LAST:event_chkStateChanged

    @SuppressWarnings("static-access")
    public void loadform() {
        try {
            jTKyThi.setModel(Cl_Client.c.getAllExamToTable());
            HighlighterPipeline highlighters = new HighlighterPipeline();
            highlighters.addHighlighter(new AlternateRowHighlighter().linePrinter);
            jTKyThi.setHighlighters(highlighters);
        } catch (RemoteException ex) {
            Logger.getLogger(Frm_GiaoVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk;
    private javax.swing.JCheckBox chkU;
    private com.toedter.calendar.JDateChooser dateEnd;
    private com.toedter.calendar.JDateChooser dateEndU;
    private com.toedter.calendar.JDateChooser dateStart;
    private com.toedter.calendar.JDateChooser dateStartU;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JComboBox jCbDoKho;
    private javax.swing.JComboBox jCbDoKhoE;
    private javax.swing.JComboBox jCbMonThi;
    private javax.swing.JComboBox jCbMonThiE;
    private javax.swing.JComboBox jCbSoLuotLam;
    private javax.swing.JComboBox jCbSoLuotLamE;
    private javax.swing.JButton jCbXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable jTKyThi;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblDe;
    private javax.swing.JLabel lblDe1;
    private javax.swing.JLabel lblKho;
    private javax.swing.JLabel lblKho1;
    private javax.swing.JLabel lblTb;
    private javax.swing.JLabel lblTb1;
    private javax.swing.JTextField txtDSMonThi;
    private javax.swing.JTextField txtDSTenKyThi;
    private javax.swing.JTextField txtIdKyThi;
    private javax.swing.JTextField txtSoCauHoi;
    private javax.swing.JTextField txtSoCauHoiU;
    private javax.swing.JTextField txtTenKyThi;
    private javax.swing.JTextField txtTenKyThiE;
    private javax.swing.JTextField txtThoiGianLamBai;
    private javax.swing.JTextField txtThoiGianLamBaiE;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void loadPanel() {
        try {
            jTKyThi.setModel(Cl_Client.c.getAllExamToTable());
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_KyThi.class.getName()).log(Level.SEVERE, null, ex);
        }
        HighlighterPipeline highlighters = new HighlighterPipeline();
        highlighters.addHighlighter(new AlternateRowHighlighter().linePrinter);
        jTKyThi.setHighlighters(highlighters);

        chk.setSelected(false);
        txtSoCauHoi.setVisible(false);

        jCbSoLuotLam.removeAllItems();
        jCbSoLuotLam.addItem("0");
        for (int i = 0; i <= 10; i++) {
            jCbSoLuotLam.addItem("" + i);
        }

        // Mon thi
        jCbMonThi.removeAllItems();
        jCbMonThi.addItem("  ---  ");
        try {
            List<Subject> lstSubject = Cl_Client.c.getAllSubject();
            for (int i = 0; i < lstSubject.size(); i++) {
                jCbMonThi.addItem(lstSubject.get(i));
            }
        } catch (Exception e) {
        }

        // Do kho'
        jCbDoKho.removeAllItems();
        jCbDoKho.addItem("  ---  ");
        try {
            List<LevelAll> lst = Cl_Client.c.getAllLevel();
            for (int i = 0; i < lst.size(); i++) {
                jCbDoKho.addItem(lst.get(i));
            }
        } catch (Exception e) {
        }


        // Update

        jCbSoLuotLamE.removeAllItems();
        for (int i = 0; i <= 10; i++) {
            jCbSoLuotLamE.addItem("" + i);
        }
        // Mon thi
        jCbMonThiE.removeAllItems();
        jCbMonThiE.addItem("  ---  ");
        try {
            List<Subject> lstSubject = Cl_Client.c.getAllSubject();
            for (int i = 0; i < lstSubject.size(); i++) {
                jCbMonThiE.addItem(lstSubject.get(i));
            }
        } catch (Exception e) {
        }
        // Do kho'
        jCbDoKhoE.removeAllItems();
        jCbDoKhoE.addItem("  ---  ");
        try {
            List<LevelAll> lst = Cl_Client.c.getAllLevel();
            for (int i = 0; i < lst.size(); i++) {
                jCbDoKhoE.addItem(lst.get(i));
            }
        } catch (Exception e) {
        }
    }

    private void reset() {
        txtTenKyThiE.setText("");
        jCbDoKhoE.setSelectedIndex(0);
        txtThoiGianLamBaiE.setText("");
        jCbSoLuotLamE.setSelectedIndex(0);
        jCbMonThiE.setSelectedIndex(0);
        dateStartU.setDate(null);
        dateEndU.setDate(null);
        txtUserName.setText("");
        txtTotal.setText("0");

    }

    private void resetThemMoi() {
        txtTenKyThi.setText("");
        jCbDoKho.setSelectedIndex(0);
        txtThoiGianLamBai.setText("");
        jCbSoLuotLam.setSelectedIndex(0);
        jCbMonThi.setSelectedIndex(0);
        dateStart.setDate(null);
        dateEnd.setDate(null);
        chk.setSelected(false);

    }
}
