
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.decorator.AlternateRowHighlighter;
import org.jdesktop.swingx.decorator.Filter;
import org.jdesktop.swingx.decorator.FilterPipeline;
import org.jdesktop.swingx.decorator.HighlighterPipeline;
import org.jdesktop.swingx.decorator.PatternFilter;
import vn.com.dva.entities.Question;
import vn.com.dva.entities.Subject;
import vn.com.dva.entities.Users;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pnl_CauHoi.java
 *
 * Created on Aug 28, 2011, 6:21:34 PM
 */

/**
 *
 * @author VietAnh
 */
public class Pnl_CauHoi extends javax.swing.JPanel {
    private byte[] dataImages;
    private byte[] dataImagesU;
    /** Creates new form Pnl_CauHoi */
    public Pnl_CauHoi() {
        initComponents();
        loadPanel();
        loadform();
    }

    public byte[] getDataImages() {
        return dataImages;
    }
    public byte[] getDataImagesU() {
        return dataImagesU;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnl = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdCauHoi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMonHoc = new javax.swing.JTextField();
        txtNoiDung = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCauHoi = new org.jdesktop.swingx.JXTable();
        jPanel2 = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCbMonThi = new javax.swing.JComboBox();
        btnThem = new javax.swing.JButton();
        txtTieuDe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTpNoiDung = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jRdA = new javax.swing.JRadioButton();
        jRdC = new javax.swing.JRadioButton();
        jRdB = new javax.swing.JRadioButton();
        jRdD = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTpA = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTpB = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTpC = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTpD = new javax.swing.JTextPane();
        jPanel6 = new javax.swing.JPanel();
        jCbDoKho = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTieuDe1 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTpNoiDung1 = new javax.swing.JTextPane();
        lblPhoto1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jCbMonThi1 = new javax.swing.JComboBox();
        jPanel9 = new javax.swing.JPanel();
        jCbDoKho1 = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        jRdA1 = new javax.swing.JRadioButton();
        jRdC1 = new javax.swing.JRadioButton();
        jRdB1 = new javax.swing.JRadioButton();
        jRdD1 = new javax.swing.JRadioButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTpA1 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTpB1 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTpC1 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTpD1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTCauHoiU = new org.jdesktop.swingx.JXTable();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc Danh Sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel1.setText("Id Câu Hỏi");

        txtIdCauHoi.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtIdCauHoiCaretUpdate(evt);
            }
        });

        jLabel2.setText("Nội Dung Câu Hỏi");

        jLabel3.setText("Môn Học");

        txtMonHoc.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtMonHocCaretUpdate(evt);
            }
        });

        txtNoiDung.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNoiDungCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMonHoc)
                            .addComponent(txtIdCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))))
                .addGap(460, 460, 460))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIdCauHoi, txtMonHoc, txtNoiDung});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtIdCauHoi, txtMonHoc, txtNoiDung});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        jTCauHoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTCauHoi);

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Danh Sách", pnl);

        lblPhoto.setText("jLabel3");
        lblPhoto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lblPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhotoMouseClicked(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Môn Học"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbMonThi, 0, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel6.setText("Tiêu đề câu hỏi");

        jTpNoiDung.setBorder(javax.swing.BorderFactory.createTitledBorder("Nội dung câu hỏi"));
        jScrollPane2.setViewportView(jTpNoiDung);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Đáp Án"));

        buttonGroup.add(jRdA);
        jRdA.setText("A");
        jRdA.setBorderPainted(true);

        buttonGroup.add(jRdC);
        jRdC.setText("C");
        jRdC.setBorderPainted(true);

        buttonGroup.add(jRdB);
        jRdB.setText("B");
        jRdB.setBorderPainted(true);

        buttonGroup.add(jRdD);
        jRdD.setText("D");
        jRdD.setBorderPainted(true);

        jScrollPane3.setViewportView(jTpA);

        jScrollPane4.setViewportView(jTpB);

        jScrollPane5.setViewportView(jTpC);

        jScrollPane6.setViewportView(jTpD);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRdA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRdC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5)))
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRdB)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jRdD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jRdA))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jRdC)))
                    .addComponent(jRdB)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jRdD))))
                .addGap(149, 149, 149))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Độ Khó"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbDoKho, 0, 174, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txtTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Thêm Mới", jPanel2);

        jLabel7.setText("Tiêu đề câu hỏi");

        jTpNoiDung1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nội dung câu hỏi"));
        jScrollPane8.setViewportView(jTpNoiDung1);

        lblPhoto1.setText("jLabel3");
        lblPhoto1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lblPhoto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPhoto1MouseClicked(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Môn Học"));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jCbMonThi1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbMonThi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Độ Khó"));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCbDoKho1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCbDoKho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Đáp Án"));

        buttonGroup1.add(jRdA1);
        jRdA1.setText("A");
        jRdA1.setBorderPainted(true);

        buttonGroup1.add(jRdC1);
        jRdC1.setText("C");
        jRdC1.setBorderPainted(true);

        buttonGroup1.add(jRdB1);
        jRdB1.setText("B");
        jRdB1.setBorderPainted(true);

        buttonGroup1.add(jRdD1);
        jRdD1.setText("D");
        jRdD1.setBorderPainted(true);

        jScrollPane9.setViewportView(jTpA1);

        jScrollPane10.setViewportView(jTpB1);

        jScrollPane11.setViewportView(jTpC1);

        jScrollPane12.setViewportView(jTpD1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jRdA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jRdC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jRdB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jRdD1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane12)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRdA1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(jRdC1)
                                .addGap(16, 16, 16))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))))
                    .addComponent(jRdB1)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jRdD1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jButton1.setText("Sửa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTieuDe1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(lblPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, 0, 129, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblPhoto1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTieuDe1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTCauHoiU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTCauHoiU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTCauHoiUMouseReleased(evt);
            }
        });
        jScrollPane7.setViewportView(jTCauHoiU);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Chỉnh Sửa", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdCauHoiCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtIdCauHoiCaretUpdate
        // TODO add your handling code here:
        jTCauHoi.setFilters(new FilterPipeline(
                    new Filter[] { new PatternFilter(txtIdCauHoi.getText()+".*", 0, 0) , new PatternFilter(txtMonHoc.getText()+".*", 0, 1) , new PatternFilter(txtNoiDung.getText()+".*", 0, 2)}));
        
        jTCauHoiU.setFilters(new FilterPipeline(
                    new Filter[] { new PatternFilter(txtIdCauHoi.getText()+".*", 0, 0) , new PatternFilter(txtMonHoc.getText()+".*", 0, 1) , new PatternFilter(txtNoiDung.getText()+".*", 0, 2)}));
        
    }//GEN-LAST:event_txtIdCauHoiCaretUpdate

    private void txtMonHocCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtMonHocCaretUpdate
        // TODO add your handling code here:
        jTCauHoi.setFilters(new FilterPipeline(
                    new Filter[] { new PatternFilter(txtIdCauHoi.getText()+".*", 0, 0) , new PatternFilter(txtMonHoc.getText()+".*", 0, 1) , new PatternFilter(txtNoiDung.getText()+".*", 0, 2)}));
        jTCauHoiU.setFilters(new FilterPipeline(
                    new Filter[] { new PatternFilter(txtIdCauHoi.getText()+".*", 0, 0) , new PatternFilter(txtMonHoc.getText()+".*", 0, 1) , new PatternFilter(txtNoiDung.getText()+".*", 0, 2)}));

    }//GEN-LAST:event_txtMonHocCaretUpdate

    private void txtNoiDungCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNoiDungCaretUpdate
        // TODO add your handling code here:
        jTCauHoi.setFilters(new FilterPipeline(
                    new Filter[] { new PatternFilter(txtIdCauHoi.getText()+".*", 0, 0) , new PatternFilter(txtMonHoc.getText()+".*", 0, 1) , new PatternFilter(txtNoiDung.getText()+".*", 0, 2)}));

        jTCauHoiU.setFilters(new FilterPipeline(
                    new Filter[] { new PatternFilter(txtIdCauHoi.getText()+".*", 0, 0) , new PatternFilter(txtMonHoc.getText()+".*", 0, 1) , new PatternFilter(txtNoiDung.getText()+".*", 0, 2)}));

    }//GEN-LAST:event_txtNoiDungCaretUpdate

private void lblPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhotoMouseClicked
// TODO add your handling code here:
    if (evt.getClickCount() == 2) {
        loadImage();
    }
}//GEN-LAST:event_lblPhotoMouseClicked

private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // TODO add your handling code here:
            if (jTpNoiDung.getText().equals("")) {
                Cl_Client.ShowError("Bạn chưa nhập nội dung câu hỏi");
                return;
            }
            if (jTpA.getText().equals("") || jTpB.getText().equals("") || jTpC.getText().equals("") || jTpD.getText().equals("")) {
                Cl_Client.ShowError("Bạn phải nhập đầy đủ đáp án");
            }
            String da = "";
            if (jRdA.isSelected()) {
                da = "A";
            }
            if (jRdB.isSelected()) {
                da = "B";
            }
            if (jRdC.isSelected()) {
                da = "C";
            }
            if (jRdD.isSelected()) {
                da = "D";
            }
            if (da.equals("")) {
                Cl_Client.ShowError("Bạn phải chọn 1 đáp án đúng");
                return;
            }

            
            String usernameCreate = User.username ;
            Long idUser = null ;
            try {
                Users u = Cl_Client.c.getUserByUserName(usernameCreate);
                idUser = u.getUserID();
            } catch (Exception e) {
                idUser = null ;
            }
            
            Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                String dateCreate = sdf.format(d);
                
            String tieude = txtTieuDe.getText();
            byte[] image = getDataImages();
            Subject s = (Subject) jCbMonThi.getSelectedItem();
            Question bean = new Question(tieude, idUser , jCbDoKho.getSelectedIndex()+1 , s.getSubjecId() ,jTpNoiDung.getText(),da, jTpA.getText(), jTpB.getText(),
                    jTpC.getText(), jTpD.getText(), dateCreate, image );
            
            if (Cl_Client.c.insertQuestion(bean)){
                resetAll();
                loadform();
            }
            else {
                JOptionPane.showMessageDialog(null, "Loi");
            }
            

        } catch (RemoteException ex) {
            Logger.getLogger(FrmThemCauHoi.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnThemActionPerformed

private void lblPhoto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhoto1MouseClicked
// TODO add your handling code here:
    if (evt.getClickCount() == 2) {
        loadImageU();
    }
}//GEN-LAST:event_lblPhoto1MouseClicked

private void jTCauHoiUMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCauHoiUMouseReleased
// TODO add your handling code here:
        Long id = Main.client.getIDTable(jTCauHoiU);
        if (!id.equals("") || id!= -1) {
            try {
                Question bean = Cl_Client.c.getQuestiontByID(id);
                txtTieuDe1.setText(bean.getQuestionTitle());
                jTpNoiDung1.setText(bean.getContent());
                int level = bean.getLevelID();
                if (level == 1)
                    jCbDoKho1.setSelectedIndex(0);
                else if (level == 2)
                    jCbDoKho1.setSelectedIndex(1);
                else jCbDoKho1.setSelectedIndex(2);
                
                Subject s = Cl_Client.c.getSubjectByID(bean.getSubjectID());
                jCbMonThi1.getModel().setSelectedItem(s);
                
                
                String answer = bean.getAnswer() ;
                
                buttonGroup1.clearSelection();
                if (answer.endsWith("A"))
                    jRdA1.setSelected(true);
                if (answer.endsWith("B"))
                    jRdB1.setSelected(true);
                if (answer.endsWith("C"))
                    jRdC1.setSelected(true);
                if (answer.endsWith("D"))
                    jRdD1.setSelected(true);
                
                jTpA1.setText(bean.getChooseA());
                jTpB1.setText(bean.getChooseB());
                jTpC1.setText(bean.getChooseC());
                jTpD1.setText(bean.getChooseD());
                dataImagesU = bean.getPicture();
                showImageU();
            } catch (Exception ex) {
            }
        }
}//GEN-LAST:event_jTCauHoiUMouseReleased

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            if (jTCauHoi.getSelectedRow() < 0) {
                Cl_Client.ShowError("Hãy chọn 1 câu hỏi ");
                return ;
            }
                    if (jTpNoiDung1.getText().equals("")) {
                            Cl_Client.ShowError("Bạn chưa nhập nội dung câu hỏi");
                            return;
                    }
                    if (jTpA1.getText().equals("") || jTpB1.getText().equals("") || jTpC1.getText().equals("") || jTpD1.getText().equals("")) {
                        Cl_Client.ShowError("Bạn phải nhập đầy đủ đáp án");
                    }
                    String da = "";
                    if (jRdA1.isSelected()) {
                        da = "A";
                    }
                    if (jRdB1.isSelected()) {
                        da = "B";
                    }
                    if (jRdC1.isSelected()) {
                        da = "C";
                    }
                    if (jRdD1.isSelected()) {
                        da = "D";
                    }
                    if (da.equals("")) {
                        Cl_Client.ShowError("Bạn phải chọn 1 đáp án đúng");
                        return;
                    }

                    Date d = new Date();
                        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                        String dateCreate = sdf.format(d);

                    String tieude = txtTieuDe1.getText();
                    byte[] image = getDataImagesU();
                    Subject s = (Subject) jCbMonThi1.getSelectedItem();
                    Long id = Main.client.getIDTable(jTCauHoiU);
                    Question q = Cl_Client.c.getQuestiontByID(id);
                    Question bean = new Question(id ,tieude, q.getUserID() , jCbDoKho1.getSelectedIndex()+1 , s.getSubjecId() ,jTpNoiDung1.getText(),da, jTpA1.getText(), jTpB1.getText(),
                            jTpC1.getText(), jTpD1.getText(), dateCreate, image );

                    if (Cl_Client.c.updateQuestion(bean)){
                        resetAll();
                        loadform();
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Loi");
                    }
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_CauHoi.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
                if (jTCauHoiU.getSelectedRow() < 0 ) return ;   
                Long id = Main.client.getIDTable(jTCauHoiU);
                if (Cl_Client.c.removeQuestion(id)){
                    resetAll();
                    loadform();
                }
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_CauHoi.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        loadform();
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCbDoKho;
    private javax.swing.JComboBox jCbDoKho1;
    private javax.swing.JComboBox jCbMonThi;
    private javax.swing.JComboBox jCbMonThi1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRdA;
    private javax.swing.JRadioButton jRdA1;
    private javax.swing.JRadioButton jRdB;
    private javax.swing.JRadioButton jRdB1;
    private javax.swing.JRadioButton jRdC;
    private javax.swing.JRadioButton jRdC1;
    private javax.swing.JRadioButton jRdD;
    private javax.swing.JRadioButton jRdD1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private org.jdesktop.swingx.JXTable jTCauHoi;
    private org.jdesktop.swingx.JXTable jTCauHoiU;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTpA;
    private javax.swing.JTextPane jTpA1;
    private javax.swing.JTextPane jTpB;
    private javax.swing.JTextPane jTpB1;
    private javax.swing.JTextPane jTpC;
    private javax.swing.JTextPane jTpC1;
    private javax.swing.JTextPane jTpD;
    private javax.swing.JTextPane jTpD1;
    private javax.swing.JTextPane jTpNoiDung;
    private javax.swing.JTextPane jTpNoiDung1;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPhoto1;
    private javax.swing.JPanel pnl;
    private javax.swing.JTextField txtIdCauHoi;
    private javax.swing.JTextField txtMonHoc;
    private javax.swing.JTextField txtNoiDung;
    private javax.swing.JTextField txtTieuDe;
    private javax.swing.JTextField txtTieuDe1;
    // End of variables declaration//GEN-END:variables

    private void loadPanel() {
        try {
            jTCauHoi.setModel(Cl_Client.c.getAllQuestionToTable());
            jTCauHoiU.setModel(Cl_Client.c.getAllQuestionToTable());
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_CauHoi.class.getName()).log(Level.SEVERE, null, ex);
        }
            HighlighterPipeline highlighters = new HighlighterPipeline();
            highlighters.addHighlighter(new AlternateRowHighlighter().linePrinter);
            jTCauHoi.setHighlighters(highlighters);
            jTCauHoiU.setHighlighters(highlighters);
    }
    
    
     private void resetAll()
    {
        txtTieuDe.setText("");
        jTpNoiDung.setText("");
        jTpA.setText("");
        jTpB.setText("");
        jTpC.setText("");
        jTpD.setText("");
        dataImages = null;
        showImage();
        buttonGroup.clearSelection();
        
        txtTieuDe1.setText("");
        jTpNoiDung1.setText("");
        jTpA1.setText("");
        jTpB1.setText("");
        jTpC1.setText("");
        jTpD1.setText("");
        dataImagesU = null;
        showImageU();
        buttonGroup1.clearSelection();
        
        loadPanel();
    }
      private void loadform() {
        // Độ khó
        jCbDoKho.removeAllItems();
        jCbDoKho.addItem("Dễ");
        jCbDoKho.addItem("Trung Bình");
        jCbDoKho.addItem("Khó");
        
        jCbDoKho1.removeAllItems();
        jCbDoKho1.addItem("Dễ");
        jCbDoKho1.addItem("Trung Bình");
        jCbDoKho1.addItem("Khó");
        // Môn học
        jCbMonThi.removeAllItems();
        jCbMonThi1.removeAllItems();
        List<Subject> lst ;
        try {
            lst = Cl_Client.c.getAllSubject();
            if (!lst.isEmpty())
                for (Subject bean : lst){
                    jCbMonThi.addItem(bean);
                    jCbMonThi1.addItem(bean);
                }
        } catch (RemoteException ex) {
            Logger.getLogger(FrmThemCauHoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
      private void loadImage() {
        JFileChooser fileChoise = new JFileChooser();

        fileChoise.setVisible(true);
        fileChoise.showOpenDialog(this);
        File file = fileChoise.getSelectedFile();
        if (file == null) {
            return;
        }
        if (file.length() > 1024 * 1024) {
            JOptionPane.showMessageDialog(null, "file anh qua lon");
            return;
        }
        try {
            BufferedImage biold = ImageIO.read(file);
            BufferedImage bi = new BufferedImage(lblPhoto.getSize().height, lblPhoto.getSize().width, BufferedImage.TYPE_INT_RGB);
            Graphics2D grap = bi.createGraphics();
            grap.drawImage(biold, 0, 0, lblPhoto.getSize().width, lblPhoto.getSize().height, null);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bi, "jpg", baos);
            dataImages = baos.toByteArray();
            showImage();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Khong luu duoc anh");
            return;
        }
    }
      
      
      private Icon icon;

    public void showImage() {
        if (dataImages == null) {
            lblPhoto.setText("Anh");
            lblPhoto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
            icon = new ImageIcon();
            lblPhoto.setIcon(icon);
            lblPhoto.setVisible(true);
        } else {
            lblPhoto.setText("");
            lblPhoto.setBorder(null);
            icon = new ImageIcon(dataImages);
            lblPhoto.setIcon(icon);
            lblPhoto.setVisible(true);
        }
    }

    
// --------------------------------------------------
    
      private void loadImageU() {
        JFileChooser fileChoise = new JFileChooser();

        fileChoise.setVisible(true);
        fileChoise.showOpenDialog(this);
        File file = fileChoise.getSelectedFile();
        if (file == null) {
            return;
        }
        if (file.length() > 1024 * 1024) {
            JOptionPane.showMessageDialog(null, "file anh qua lon");
            return;
        }
        try {
            BufferedImage biold = ImageIO.read(file);
            BufferedImage bi = new BufferedImage(lblPhoto1.getSize().height, lblPhoto1.getSize().width, BufferedImage.TYPE_INT_RGB);
            Graphics2D grap = bi.createGraphics();
            grap.drawImage(biold, 0, 0, lblPhoto1.getSize().width, lblPhoto1.getSize().height, null);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bi, "jpg", baos);
            dataImagesU = baos.toByteArray();
            showImageU();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Khong luu duoc anh");
            return;
        }
    }
      
      
      private Icon iconU;

    public void showImageU() {
        if (dataImagesU == null) {
            lblPhoto1.setText("Anh");
            lblPhoto1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
            iconU = new ImageIcon();
            lblPhoto1.setIcon(iconU);
            lblPhoto1.setVisible(true);
        } else {
            lblPhoto1.setText("");
            lblPhoto1.setBorder(null);
            iconU = new ImageIcon(dataImagesU);
            lblPhoto1.setIcon(iconU);
            lblPhoto1.setVisible(true);
        }
    }

    
    
    
}
