
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.decorator.AlternateRowHighlighter;
import org.jdesktop.swingx.decorator.Filter;
import org.jdesktop.swingx.decorator.FilterPipeline;
import org.jdesktop.swingx.decorator.HighlighterPipeline;
import org.jdesktop.swingx.decorator.PatternFilter;
import vn.com.dva.entities.GroupUser;
import vn.com.dva.entities.LevelAll;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pnl_DoKho.java
 *
 * Created on Aug 28, 2011, 8:21:25 PM
 */
/**
 *
 * @author VietAnh
 */
public class Pnl_DoKho extends javax.swing.JPanel {

    private final String ADMIN = "Admin";
    private final String TEACHER = "Giáo Viên";
    private final String STUDENT = "Sinh Viên";

    /** Creates new form Pnl_DoKho */
    public Pnl_DoKho() {
        initComponents();
        loadTable();
        loadTableGroup();
        InitData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtTen = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtIdDoKho = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTb = new javax.swing.JTextField();
        txtDe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenDoKho = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnHuy = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtGroupName = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMoTa1 = new javax.swing.JTextArea();
        cbxManager = new javax.swing.JComboBox();
        jCb = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenDoKhoU = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMoTaU = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        txtIDDoKhoU = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTbU = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtKhoU = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDeU = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        cbxManagerU = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jCbU = new javax.swing.JCheckBox();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtMoTa1U = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtGroupNameU = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtIdGroupU = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDoKho = new org.jdesktop.swingx.JXTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTGroupUser = new org.jdesktop.swingx.JXTable();

        setPreferredSize(new java.awt.Dimension(1100, 650));

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Độ Khó"));

        txtTen.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTenCaretUpdate(evt);
            }
        });

        jLabel19.setText("ID Độ Khó");

        txtIdDoKho.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtIdDoKhoCaretUpdate(evt);
            }
        });

        jLabel15.setText("Tên Độ Khó");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdDoKho)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtIdDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhóm Người Dùng"));

        jLabel20.setText("jLabel20");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel20)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel20)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Danh Sách", new javax.swing.ImageIcon(getClass().getResource("/resource/Filter.png")), jPanel6); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Độ Khó"));

        jLabel8.setText("Tỉ lệ câu thường");

        txtTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTbKeyPressed(evt);
            }
        });

        txtDe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDeKeyPressed(evt);
            }
        });

        jLabel6.setText("Thỉ lệ câu khó");

        jLabel3.setText("Tỉ lệ câu dễ");

        jLabel4.setText("%");

        txtKho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKhoKeyPressed(evt);
            }
        });

        jLabel2.setText("Tên Độ Khó");

        jLabel16.setText("Mô tả");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        btnHuy.setText("Làm lại");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel5.setText("%");

        jLabel7.setText("%");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel16)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(txtDe, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTb, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(txtKho, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnHuy)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addGap(79, 79, 79))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenDoKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnThem)))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhóm Người Dùng"));

        jLabel21.setText("Tên Nhóm");

        jLabel22.setText("Quyền Quản Lý");

        jLabel23.setText("Mô tả");

        txtMoTa1.setColumns(20);
        txtMoTa1.setRows(5);
        jScrollPane5.setViewportView(txtMoTa1);

        jCb.setText("Trạng Thái Kích Hoạt");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Làm Lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCb)
                                    .addComponent(cbxManager, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel23))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jCb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cbxManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Thêm Mới", new javax.swing.ImageIcon(getClass().getResource("/resource/Add.png")), jPanel5); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Độ Khó"));

        jLabel1.setText("Tên Độ Khó");

        txtMoTaU.setColumns(20);
        txtMoTaU.setRows(5);
        jScrollPane3.setViewportView(txtMoTaU);

        jLabel17.setText("Mô tả");

        txtIDDoKhoU.setEnabled(false);

        jLabel18.setText("ID Độ Khó");

        txtTbU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTbUKeyPressed(evt);
            }
        });

        jLabel9.setText("%");

        jLabel10.setText("%");

        jLabel11.setText("Tỉ lệ câu thường");

        jLabel12.setText("%");

        jLabel13.setText("Thỉ lệ câu khó");

        txtKhoU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKhoUKeyPressed(evt);
            }
        });

        jLabel14.setText("Tỉ lệ câu dễ");

        txtDeU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDeUKeyPressed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)
                        .addGap(51, 51, 51)
                        .addComponent(txtIDDoKhoU, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(txtTenDoKhoU, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel17))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(23, 23, 23)
                                .addComponent(txtTbU, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(35, 35, 35)
                                .addComponent(txtKhoU, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(44, 44, 44)
                                .addComponent(txtDeU, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnXoa))
                            .addComponent(btnSua))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtIDDoKhoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(txtTenDoKhoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel17))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtDeU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTbU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtKhoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa)
                    .addComponent(btnSua))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhóm Người Dùng"));

        cbxManagerU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxManagerUActionPerformed(evt);
            }
        });

        jLabel24.setText("Quyền Quản Lý");

        jCbU.setText("Trạng Thái Kích Hoạt");

        txtMoTa1U.setColumns(20);
        txtMoTa1U.setRows(5);
        jScrollPane6.setViewportView(txtMoTa1U);

        jLabel25.setText("Mô tả");

        jLabel26.setText("Tên Nhóm");

        jLabel27.setText("Id Nhóm");

        txtIdGroupU.setEditable(false);

        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Xóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel27)
                        .addGap(64, 64, 64)
                        .addComponent(txtIdGroupU, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26)
                                .addComponent(jLabel25))
                            .addGap(65, 65, 65)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGroupNameU, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(38, 38, 38)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCbU)
                                .addComponent(cbxManagerU, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtIdGroupU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(txtGroupNameU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel25))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(jCbU)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(cbxManagerU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(51, 51, 51)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Cập Nhật", new javax.swing.ImageIcon(getClass().getResource("/resource/Edit.png")), jPanel4); // NOI18N

        jTDoKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTDoKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTDoKhoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTDoKho);

        jTGroupUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTGroupUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTGroupUserMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTGroupUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTenCaretUpdate
        // TODO add your handling code here:
        if (!txtTen.getText().equals("")) {
            jTDoKho.setFilters(new FilterPipeline(
                    new Filter[]{new PatternFilter(txtTen.getText() + ".*", 0, 1)}));
        } else {
            jTDoKho.setFilters(null);
        }

    }//GEN-LAST:event_txtTenCaretUpdate

    private void txtIdDoKhoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtIdDoKhoCaretUpdate
        // TODO add your handling code here:
        jTDoKho.setFilters(new FilterPipeline(
                new Filter[]{new PatternFilter(txtIdDoKho.getText() + ".*", 0, 0), new PatternFilter(txtTen.getText() + ".*", 0, 1)}));
}//GEN-LAST:event_txtIdDoKhoCaretUpdate

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // TODO add your handling code here:
            if (txtTenDoKho.getText().length() <= 0) {
                return;
            }
            if (Integer.parseInt(txtDe.getText()) + Integer.parseInt(txtTb.getText()) + Integer.parseInt(txtKho.getText()) != 100) {
                JOptionPane.showConfirmDialog(null, "Tổng số khác 100% ! Vui lòng nhập lại", "Lỗi", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
                txtDe.setText("");
                txtTb.setText("");
                txtKho.setText("");
                return;
            }
            if (txtTenDoKho.getText().equals("")) {
                JOptionPane.showConfirmDialog(null, "Bạn chưa nhập tên độ khó ", "Lỗi", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(null, txtMoTa.getText());
            LevelAll bean = new LevelAll(txtTenDoKho.getText(), txtMoTa.getText(), Integer.parseInt(txtDe.getText()), Integer.parseInt(txtTb.getText()), Integer.parseInt(txtKho.getText()));
            Cl_Client.c.insertLevel(bean);
            loadTable();
            reset();
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_DoKho.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnThemActionPerformed

    private void txtKhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKhoKeyPressed
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(txtKho.getText().toString()) >= 10) {
                JOptionPane.showMessageDialog(null, "Tỉ lệ nhập phải nhỏ hơn 100");
                txtKho.setText("");
            }
        } catch (Exception e) {
        }
}//GEN-LAST:event_txtKhoKeyPressed

    private void txtTbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTbKeyPressed
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(txtTb.getText().toString()) >= 10) {
                JOptionPane.showMessageDialog(null, "Tỉ lệ nhập phải nhỏ hơn 100");
                txtTb.setText("");
            }
        } catch (Exception e) {
        }
}//GEN-LAST:event_txtTbKeyPressed

    private void txtDeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeKeyPressed
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(txtDe.getText().toString()) >= 10) {
                JOptionPane.showMessageDialog(null, "Tỉ lệ nhập phải nhỏ hơn 100");
                txtDe.setText("");
            }
        } catch (Exception e) {
        }
}//GEN-LAST:event_txtDeKeyPressed

    private void txtTbUKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTbUKeyPressed
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(txtTb.getText().toString()) >= 10) {
                JOptionPane.showMessageDialog(null, "Tỉ lệ nhập phải nhỏ hơn 100");
                txtTb.setText("");
            }
        } catch (Exception e) {
        }
}//GEN-LAST:event_txtTbUKeyPressed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:

        if (jTDoKho.getSelectedColumn() == -1) {
            JOptionPane.showConfirmDialog(null, "Vui lòng chọn 1 hàng ở dưới", "Lỗi", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Long id = Main.client.getIDTable(jTDoKho);
                LevelAll l = Cl_Client.c.getLeveltByID(id);

                if (Integer.parseInt(txtDeU.getText()) + Integer.parseInt(txtTbU.getText()) + Integer.parseInt(txtKhoU.getText()) != 100) {
                    JOptionPane.showConfirmDialog(null, "Tổng số khác 100% ! Vui lòng nhập lại", "Lỗi", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
                    txtDeU.setText("");
                    txtTbU.setText("");
                    txtKhoU.setText("");
                    return;
                }
                if (txtTenDoKhoU.getText().equals("")) {
                    JOptionPane.showConfirmDialog(null, "Bạn chưa nhập tên độ khó ", "Lỗi", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
                    return;
                }

                LevelAll bean = new LevelAll(id, txtTenDoKhoU.getText(), txtMoTaU.getText(), Integer.parseInt(txtDeU.getText()), Integer.parseInt(txtTbU.getText()), Integer.parseInt(txtKhoU.getText()));
                Cl_Client.c.updateLevel(bean);
                loadTable();
            } catch (Exception ex) {
            }
        }
}//GEN-LAST:event_btnSuaActionPerformed

    private void txtKhoUKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKhoUKeyPressed
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(txtKho.getText().toString()) >= 10) {
                JOptionPane.showMessageDialog(null, "Tỉ lệ nhập phải nhỏ hơn 100");
                txtKho.setText("");
            }
        } catch (Exception e) {
        }
}//GEN-LAST:event_txtKhoUKeyPressed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (jTDoKho.getSelectedColumn() == -1) {
            JOptionPane.showConfirmDialog(null, "Vui lòng chọn 1 hàng ở dưới", "Lỗi", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Long id = Main.client.getIDTable(jTDoKho);
                Cl_Client.c.removeLevel(id);
                loadTable();
                resetU();
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtDeUKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeUKeyPressed
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(txtDe.getText().toString()) >= 10) {
                JOptionPane.showMessageDialog(null, "Tỉ lệ nhập phải nhỏ hơn 100");
                txtDe.setText("");
            }
        } catch (Exception e) {
        }
}//GEN-LAST:event_txtDeUKeyPressed

    private void jTabbedPane2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2MouseReleased

    private void jTDoKhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTDoKhoMouseReleased
        // TODO add your handling code here:
        Long id = Main.client.getIDTable(jTDoKho);
        if (!id.equals("")) {
            try {
                LevelAll bean = Cl_Client.c.getLeveltByID(id);
                txtIDDoKhoU.setText("" + bean.getLevelAllID());
                txtMoTaU.setText(bean.getLevelDescription());
                txtTenDoKhoU.setText(bean.getLevelName());
                txtDeU.setText("" + bean.getPercentEasy());
                txtTbU.setText("" + bean.getPercentNormal());
                txtKhoU.setText("" + bean.getPercentHard());
            } catch (Exception ex) {
            }
        }
}//GEN-LAST:event_jTDoKhoMouseReleased

    private void jTGroupUserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTGroupUserMouseReleased
        // TODO add your handling code here:
        Long id = Main.client.getIDTable(jTGroupUser);
        if (!id.equals("")) {
            try {
                GroupUser bean = Cl_Client.c.getGroupByID(id);
                txtIdGroupU.setText(bean.getGroupID()+"");
                txtGroupNameU.setText(bean.getGroupName());
                txtMoTa1U.setText(bean.getGroupDescription());
                jCbU.setSelected(bean.isStatus());
                cbxManagerU.setSelectedIndex(bean.getAccessManager());
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_jTGroupUserMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            String name = txtGroupName.getText();
            String description = txtMoTa1.getText();
            int accountManager = cbxManager.getSelectedIndex();
            if (name.length() == 0 || accountManager == 0) {
                return;
            }
            if (!Cl_Client.c.checkNameGroup(name)) {
                JOptionPane.showMessageDialog(null, " Đã tồn tại nhóm người dùng này !!");
                return;
            }
            GroupUser guBean = new GroupUser();
            guBean.setGroupName(name);
            guBean.setGroupDescription(description);
            guBean.setAccessManager(accountManager);
            guBean.setStatus(jCb.isSelected());
            Cl_Client.c.insertGroupUser(guBean);
            resetGroupUser();
            loadTableGroup();
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_DoKho.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        resetGroupUser();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxManagerUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxManagerUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxManagerUActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (txtIdGroupU.getText().length()== 0) return ;
        Long id = Long.parseLong(txtIdGroupU.getText());
        if (id.equals("")) return ;
         try {
            // TODO add your handling code here:
            String name = txtGroupNameU.getText();
            String description = txtMoTa1U.getText();
            int accountManager = cbxManagerU.getSelectedIndex();
            if (name.length() == 0 || accountManager == 0) {
                return;
            }
            
            GroupUser guBean = Cl_Client.c.getGroupByID(id);
            guBean.setGroupName(name);
            guBean.setGroupDescription(description);
            guBean.setAccessManager(accountManager);
            guBean.setStatus(jCbU.isSelected());
            Cl_Client.c.updateGroupUser(guBean);
            resetGroupUserU();
            loadTableGroup();
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_DoKho.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (txtIdGroupU.getText().length()== 0) return ;
        Long id = Long.parseLong(txtIdGroupU.getText());
        try {
            Cl_Client.c.removeGroupUser(id);
        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_DoKho.class.getName()).log(Level.SEVERE, null, ex);
        }
        resetGroupUserU();
        loadTableGroup();
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox cbxManager;
    private javax.swing.JComboBox cbxManagerU;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCb;
    private javax.swing.JCheckBox jCbU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private org.jdesktop.swingx.JXTable jTDoKho;
    private org.jdesktop.swingx.JXTable jTGroupUser;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField txtDe;
    private javax.swing.JTextField txtDeU;
    private javax.swing.JTextField txtGroupName;
    private javax.swing.JTextField txtGroupNameU;
    private javax.swing.JTextField txtIDDoKhoU;
    private javax.swing.JTextField txtIdDoKho;
    private javax.swing.JTextField txtIdGroupU;
    private javax.swing.JTextField txtKho;
    private javax.swing.JTextField txtKhoU;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextArea txtMoTa1;
    private javax.swing.JTextArea txtMoTa1U;
    private javax.swing.JTextArea txtMoTaU;
    private javax.swing.JTextField txtTb;
    private javax.swing.JTextField txtTbU;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenDoKho;
    private javax.swing.JTextField txtTenDoKhoU;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        try {
            jTDoKho.setModel(Cl_Client.c.getAllLevelToTable());
            HighlighterPipeline highlighters = new HighlighterPipeline();
            highlighters.addHighlighter(new AlternateRowHighlighter().linePrinter);
            jTDoKho.setHighlighters(highlighters);
        } catch (RemoteException ex) {
            Logger.getLogger(Frm_GiaoVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadTableGroup() {
        try {
            jTGroupUser.setModel(Cl_Client.c.getAllGroupUsertoTable());
            HighlighterPipeline highlighters = new HighlighterPipeline();
            highlighters.addHighlighter(new AlternateRowHighlighter().linePrinter);
            jTGroupUser.setHighlighters(highlighters);
        } catch (RemoteException ex) {
            Logger.getLogger(Frm_GiaoVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void reset() {
        txtTenDoKho.setText("");
        txtMoTa.setText("");
        txtDe.setText("");
        txtTb.setText("");
        txtKho.setText("");
    }

    private void resetU() {
        txtIDDoKhoU.setText("");
        txtTenDoKhoU.setText("");
        txtMoTaU.setText("");
        txtDeU.setText("");
        txtTbU.setText("");
        txtKhoU.setText("");

    }

    private void InitData() {
        jCb.setSelected(false);
        cbxManager.removeAllItems();
        cbxManager.addItem("Lựa Chọn");
        cbxManager.addItem(ADMIN);
        cbxManager.addItem(TEACHER);
        cbxManager.addItem(STUDENT);
        
        jCbU.setSelected(false);
        cbxManagerU.removeAllItems();
        cbxManagerU.addItem("Lựa Chọn");
        cbxManagerU.addItem(ADMIN);
        cbxManagerU.addItem(TEACHER);
        cbxManagerU.addItem(STUDENT);
    }

    private void resetGroupUser() {
        txtGroupName.setText("");
        txtMoTa1.setText("");
        jCb.setSelected(false);
        cbxManager.setSelectedIndex(0);
    }

    private void resetGroupUserU() {
        txtIdGroupU.setText("");
        txtGroupNameU.setText("");
        txtMoTa1U.setText("");
        jCbU.setSelected(false);
        cbxManagerU.setSelectedIndex(0);
    }
}
