
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.RemoteException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.japura.gui.LinkLabel;
import vn.com.dva.entities.News;
import vn.com.dva.entities.Users;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pnl_TinTuc.java
 *
 * Created on 18-03-2012, 23:59:30
 */
/**
 *
 * @author VietAnh
 */
public class Pnl_TinTuc extends javax.swing.JPanel implements ActionListener {

    private int NUMBER_DEFAULT = 5;
    private List<News> lst;
    private int status = 0;

    /** Creates new form Pnl_TinTuc */
    public Pnl_TinTuc() {
        initComponents();

        Init();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new org.japura.gui.LinkLabel();
        lbl2 = new org.japura.gui.LinkLabel();
        lbl3 = new org.japura.gui.LinkLabel();
        lbl4 = new org.japura.gui.LinkLabel();
        lbl5 = new org.japura.gui.LinkLabel();
        jLabel1 = new javax.swing.JLabel();
        lblOld = new org.japura.gui.LinkLabel();
        lblNew = new org.japura.gui.LinkLabel();

        lbl1.setText("linkLabel1");
        lbl1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        lbl2.setText("linkLabel1");
        lbl2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        lbl3.setText("linkLabel1");
        lbl3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        lbl4.setText("linkLabel1");
        lbl4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        lbl5.setText("linkLabel1");
        lbl5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tin Tức");

        lblOld.setText("Cũ Hơn");
        lblOld.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblNew.setText("Mới Hơn");
        lblNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lblNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private org.japura.gui.LinkLabel lbl1;
    private org.japura.gui.LinkLabel lbl2;
    private org.japura.gui.LinkLabel lbl3;
    private org.japura.gui.LinkLabel lbl4;
    private org.japura.gui.LinkLabel lbl5;
    private org.japura.gui.LinkLabel lblNew;
    private org.japura.gui.LinkLabel lblOld;
    // End of variables declaration//GEN-END:variables
    private JLabel lbl = new JLabel();
    private JLabel lblUser = new JLabel();
    private JLabel lblDateCreate = new JLabel();
    private JLabel lblContent = new JLabel();
    private LinkLabel lblQ = new LinkLabel();

    private void Init() {
        try {
            lbl1.addActionListener(this);
            lbl2.addActionListener(this);
            lbl3.addActionListener(this);
            lbl4.addActionListener(this);
            lbl5.addActionListener(this);
            lst = Cl_Client.c.getAllNews();
            int n = lst.size();
            status = 0;
            showOlderNewer();

            lblOld.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    status++;
                    showOlderNewer();
                }
            });

            lblNew.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    //JOptionPane.showMessageDialog(null, "aaaaa");
                    status--;
                    showOlderNewer();
                }
            });

        } catch (RemoteException ex) {
            Logger.getLogger(Pnl_TinTuc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void showOlderNewer() {
        int n = lst.size();
        int i = status * NUMBER_DEFAULT;
        resetLabelLink();
        if (n > i) {
            setLabelLink(lbl1, lst.get(i));
        }
        if (n > i + 1) {
            setLabelLink(lbl2, lst.get(i + 1));
        }
        if (n > i + 2) {
            setLabelLink(lbl3, lst.get(i + 2));
        }
        if (n > i + 3) {
            setLabelLink(lbl4, lst.get(i + 3));
        }
        if (n > i + 4) {
            setLabelLink(lbl5, lst.get(i + 4));
        }

        if (status < (n / NUMBER_DEFAULT)) {
            lblOld.setEnabled(true);
        } else {
            lblOld.setEnabled(false);
        }
        if (status > 0) {
            lblNew.setEnabled(true);
        } else {
            lblNew.setEnabled(false);
        }

    }

    private void setLabelLink(LinkLabel lbl, final News bean) {
        lbl.setText(bean.getTitle());
    }
    private void resetLabelLink(){
        lbl1.setText("");
        lbl2.setText("");
        lbl3.setText("");
        lbl4.setText("");
        lbl5.setText("");
    }

    private void showNew(News bean) {
        initComponents();
        this.removeAll();

        setLayout(new BorderLayout());
        lbl = new JLabel(bean.getTitle());
        lbl.setFont(new Font("Arial", WIDTH, 30));
        
        
        Users u;
        try {
            u = Cl_Client.c.getUserByID(bean.getIdUser());
            lblUser.setText("Người Đăng : "+ u.getUserName());
        } catch (RemoteException ex) {
            
        }
        
        lblDateCreate.setText("Ngày Đăng : "+ bean.getDateCreate());
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel,  BoxLayout.Y_AXIS));
        
        panel.add(lbl);
        panel.add(lblUser);
        panel.add(lblDateCreate);
        
        this.add(panel , BorderLayout.NORTH);
//        this.add(lblUser,BorderLayout.NORTH);
//        this.add(lblDateCreate,BorderLayout.NORTH);
//        
//        this.add(lbl, BorderLayout.NORTH);
        lblContent = new JLabel(bean.getContent());
        this.add(lblContent, BorderLayout.CENTER);

        
        lblQ.setText("Quay Lai");
        this.add(lblQ, BorderLayout.SOUTH);
        lblQ.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                back();

            }
        });

        this.repaint();
        this.setVisible(true);

    }

    private void back() {
        this.removeAll();
        initComponents();
        Init();
        this.repaint();
        this.setVisible(true);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == lbl1) {
            News news = lst.get(status * NUMBER_DEFAULT);
            showNew(news);
        }
        if (e.getSource() == lbl2) {
            News news = lst.get(status * NUMBER_DEFAULT + 1);
            showNew(news);
        }
        if (e.getSource() == lbl3) {
            News news = lst.get(status * NUMBER_DEFAULT + 2);
            showNew(news);
        }
        if (e.getSource() == lbl4) {
            News news = lst.get(status * NUMBER_DEFAULT + 3);
            showNew(news);
        }
        if (e.getSource() == lbl5) {
            News news = lst.get(status * NUMBER_DEFAULT + 4);
            showNew(news);
        }
    }
}
